// Copyright (c) 2024 Tencent Inc.
// SPDX-License-Identifier: Apache-2.0
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.3
// source: api/v1/network_agent.proto

package networkagentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NetworkAgent_EnsureNetwork_FullMethodName    = "/network_agent.api.v1.NetworkAgent/EnsureNetwork"
	NetworkAgent_ReleaseNetwork_FullMethodName   = "/network_agent.api.v1.NetworkAgent/ReleaseNetwork"
	NetworkAgent_ReconcileNetwork_FullMethodName = "/network_agent.api.v1.NetworkAgent/ReconcileNetwork"
	NetworkAgent_GetNetwork_FullMethodName       = "/network_agent.api.v1.NetworkAgent/GetNetwork"
	NetworkAgent_Health_FullMethodName           = "/network_agent.api.v1.NetworkAgent/Health"
	NetworkAgent_ListNetworks_FullMethodName     = "/network_agent.api.v1.NetworkAgent/ListNetworks"
)

// NetworkAgentClient is the client API for NetworkAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NetworkAgentClient interface {
	// Ensure the target sandbox reaches desired network state.
	EnsureNetwork(ctx context.Context, in *EnsureNetworkRequest, opts ...grpc.CallOption) (*EnsureNetworkResponse, error)
	// Release all resources associated with a network handle/sandbox.
	ReleaseNetwork(ctx context.Context, in *ReleaseNetworkRequest, opts ...grpc.CallOption) (*ReleaseNetworkResponse, error)
	// Reconcile observed state back to desired spec.
	ReconcileNetwork(ctx context.Context, in *ReconcileNetworkRequest, opts ...grpc.CallOption) (*ReconcileNetworkResponse, error)
	// Get latest known network state for a sandbox/handle.
	GetNetwork(ctx context.Context, in *GetNetworkRequest, opts ...grpc.CallOption) (*GetNetworkResponse, error)
	// Basic liveness/readiness probe.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// List all managed network states.
	ListNetworks(ctx context.Context, in *ListNetworksRequest, opts ...grpc.CallOption) (*ListNetworksResponse, error)
}

type networkAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewNetworkAgentClient(cc grpc.ClientConnInterface) NetworkAgentClient {
	return &networkAgentClient{cc}
}

func (c *networkAgentClient) EnsureNetwork(ctx context.Context, in *EnsureNetworkRequest, opts ...grpc.CallOption) (*EnsureNetworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnsureNetworkResponse)
	err := c.cc.Invoke(ctx, NetworkAgent_EnsureNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkAgentClient) ReleaseNetwork(ctx context.Context, in *ReleaseNetworkRequest, opts ...grpc.CallOption) (*ReleaseNetworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseNetworkResponse)
	err := c.cc.Invoke(ctx, NetworkAgent_ReleaseNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkAgentClient) ReconcileNetwork(ctx context.Context, in *ReconcileNetworkRequest, opts ...grpc.CallOption) (*ReconcileNetworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReconcileNetworkResponse)
	err := c.cc.Invoke(ctx, NetworkAgent_ReconcileNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkAgentClient) GetNetwork(ctx context.Context, in *GetNetworkRequest, opts ...grpc.CallOption) (*GetNetworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNetworkResponse)
	err := c.cc.Invoke(ctx, NetworkAgent_GetNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkAgentClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, NetworkAgent_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkAgentClient) ListNetworks(ctx context.Context, in *ListNetworksRequest, opts ...grpc.CallOption) (*ListNetworksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNetworksResponse)
	err := c.cc.Invoke(ctx, NetworkAgent_ListNetworks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NetworkAgentServer is the server API for NetworkAgent service.
// All implementations must embed UnimplementedNetworkAgentServer
// for forward compatibility.
type NetworkAgentServer interface {
	// Ensure the target sandbox reaches desired network state.
	EnsureNetwork(context.Context, *EnsureNetworkRequest) (*EnsureNetworkResponse, error)
	// Release all resources associated with a network handle/sandbox.
	ReleaseNetwork(context.Context, *ReleaseNetworkRequest) (*ReleaseNetworkResponse, error)
	// Reconcile observed state back to desired spec.
	ReconcileNetwork(context.Context, *ReconcileNetworkRequest) (*ReconcileNetworkResponse, error)
	// Get latest known network state for a sandbox/handle.
	GetNetwork(context.Context, *GetNetworkRequest) (*GetNetworkResponse, error)
	// Basic liveness/readiness probe.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// List all managed network states.
	ListNetworks(context.Context, *ListNetworksRequest) (*ListNetworksResponse, error)
	mustEmbedUnimplementedNetworkAgentServer()
}

// UnimplementedNetworkAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNetworkAgentServer struct{}

func (UnimplementedNetworkAgentServer) EnsureNetwork(context.Context, *EnsureNetworkRequest) (*EnsureNetworkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnsureNetwork not implemented")
}
func (UnimplementedNetworkAgentServer) ReleaseNetwork(context.Context, *ReleaseNetworkRequest) (*ReleaseNetworkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseNetwork not implemented")
}
func (UnimplementedNetworkAgentServer) ReconcileNetwork(context.Context, *ReconcileNetworkRequest) (*ReconcileNetworkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReconcileNetwork not implemented")
}
func (UnimplementedNetworkAgentServer) GetNetwork(context.Context, *GetNetworkRequest) (*GetNetworkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNetwork not implemented")
}
func (UnimplementedNetworkAgentServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedNetworkAgentServer) ListNetworks(context.Context, *ListNetworksRequest) (*ListNetworksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNetworks not implemented")
}
func (UnimplementedNetworkAgentServer) mustEmbedUnimplementedNetworkAgentServer() {}
func (UnimplementedNetworkAgentServer) testEmbeddedByValue()                      {}

// UnsafeNetworkAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NetworkAgentServer will
// result in compilation errors.
type UnsafeNetworkAgentServer interface {
	mustEmbedUnimplementedNetworkAgentServer()
}

func RegisterNetworkAgentServer(s grpc.ServiceRegistrar, srv NetworkAgentServer) {
	// If the following call panics, it indicates UnimplementedNetworkAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NetworkAgent_ServiceDesc, srv)
}

func _NetworkAgent_EnsureNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnsureNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkAgentServer).EnsureNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkAgent_EnsureNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkAgentServer).EnsureNetwork(ctx, req.(*EnsureNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkAgent_ReleaseNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkAgentServer).ReleaseNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkAgent_ReleaseNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkAgentServer).ReleaseNetwork(ctx, req.(*ReleaseNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkAgent_ReconcileNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReconcileNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkAgentServer).ReconcileNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkAgent_ReconcileNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkAgentServer).ReconcileNetwork(ctx, req.(*ReconcileNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkAgent_GetNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkAgentServer).GetNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkAgent_GetNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkAgentServer).GetNetwork(ctx, req.(*GetNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkAgent_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkAgentServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkAgent_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkAgentServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkAgent_ListNetworks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNetworksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkAgentServer).ListNetworks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkAgent_ListNetworks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkAgentServer).ListNetworks(ctx, req.(*ListNetworksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NetworkAgent_ServiceDesc is the grpc.ServiceDesc for NetworkAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NetworkAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "network_agent.api.v1.NetworkAgent",
	HandlerType: (*NetworkAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnsureNetwork",
			Handler:    _NetworkAgent_EnsureNetwork_Handler,
		},
		{
			MethodName: "ReleaseNetwork",
			Handler:    _NetworkAgent_ReleaseNetwork_Handler,
		},
		{
			MethodName: "ReconcileNetwork",
			Handler:    _NetworkAgent_ReconcileNetwork_Handler,
		},
		{
			MethodName: "GetNetwork",
			Handler:    _NetworkAgent_GetNetwork_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _NetworkAgent_Health_Handler,
		},
		{
			MethodName: "ListNetworks",
			Handler:    _NetworkAgent_ListNetworks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/network_agent.proto",
}
