//
//Copyright The containerd Authors.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: api/services/cubehost/v1/hostimage.proto

package cubehost

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

const _ = grpc.SupportPackageIsVersion7

const (
	CubeHostImageService_ReverseStreamForwardImage_FullMethodName = "/cubelet.services.cubebox.hostimage.v1.CubeHostImageService/ReverseStreamForwardImage"
	CubeHostImageService_ListImages_FullMethodName                = "/cubelet.services.cubebox.hostimage.v1.CubeHostImageService/ListImages"
)

type CubeHostImageServiceClient interface {
	ReverseStreamForwardImage(ctx context.Context, opts ...grpc.CallOption) (CubeHostImageService_ReverseStreamForwardImageClient, error)

	ListImages(ctx context.Context, in *ListImagesRequest, opts ...grpc.CallOption) (*ListImagesResponse, error)
}

type cubeHostImageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCubeHostImageServiceClient(cc grpc.ClientConnInterface) CubeHostImageServiceClient {
	return &cubeHostImageServiceClient{cc}
}

func (c *cubeHostImageServiceClient) ReverseStreamForwardImage(ctx context.Context, opts ...grpc.CallOption) (CubeHostImageService_ReverseStreamForwardImageClient, error) {
	stream, err := c.cc.NewStream(ctx, &CubeHostImageService_ServiceDesc.Streams[0], CubeHostImageService_ReverseStreamForwardImage_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &cubeHostImageServiceReverseStreamForwardImageClient{stream}
	return x, nil
}

type CubeHostImageService_ReverseStreamForwardImageClient interface {
	Send(*ClientMessage) error
	Recv() (*ServerMessage, error)
	grpc.ClientStream
}

type cubeHostImageServiceReverseStreamForwardImageClient struct {
	grpc.ClientStream
}

func (x *cubeHostImageServiceReverseStreamForwardImageClient) Send(m *ClientMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *cubeHostImageServiceReverseStreamForwardImageClient) Recv() (*ServerMessage, error) {
	m := new(ServerMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cubeHostImageServiceClient) ListImages(ctx context.Context, in *ListImagesRequest, opts ...grpc.CallOption) (*ListImagesResponse, error) {
	out := new(ListImagesResponse)
	err := c.cc.Invoke(ctx, CubeHostImageService_ListImages_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type CubeHostImageServiceServer interface {
	ReverseStreamForwardImage(CubeHostImageService_ReverseStreamForwardImageServer) error

	ListImages(context.Context, *ListImagesRequest) (*ListImagesResponse, error)
	mustEmbedUnimplementedCubeHostImageServiceServer()
}

type UnimplementedCubeHostImageServiceServer struct {
}

func (UnimplementedCubeHostImageServiceServer) ReverseStreamForwardImage(CubeHostImageService_ReverseStreamForwardImageServer) error {
	return status.Errorf(codes.Unimplemented, "method ReverseStreamForwardImage not implemented")
}
func (UnimplementedCubeHostImageServiceServer) ListImages(context.Context, *ListImagesRequest) (*ListImagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListImages not implemented")
}
func (UnimplementedCubeHostImageServiceServer) mustEmbedUnimplementedCubeHostImageServiceServer() {}

type UnsafeCubeHostImageServiceServer interface {
	mustEmbedUnimplementedCubeHostImageServiceServer()
}

func RegisterCubeHostImageServiceServer(s grpc.ServiceRegistrar, srv CubeHostImageServiceServer) {
	s.RegisterService(&CubeHostImageService_ServiceDesc, srv)
}

func _CubeHostImageService_ReverseStreamForwardImage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CubeHostImageServiceServer).ReverseStreamForwardImage(&cubeHostImageServiceReverseStreamForwardImageServer{stream})
}

type CubeHostImageService_ReverseStreamForwardImageServer interface {
	Send(*ServerMessage) error
	Recv() (*ClientMessage, error)
	grpc.ServerStream
}

type cubeHostImageServiceReverseStreamForwardImageServer struct {
	grpc.ServerStream
}

func (x *cubeHostImageServiceReverseStreamForwardImageServer) Send(m *ServerMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *cubeHostImageServiceReverseStreamForwardImageServer) Recv() (*ClientMessage, error) {
	m := new(ClientMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _CubeHostImageService_ListImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CubeHostImageServiceServer).ListImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CubeHostImageService_ListImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CubeHostImageServiceServer).ListImages(ctx, req.(*ListImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var CubeHostImageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cubelet.services.cubebox.hostimage.v1.CubeHostImageService",
	HandlerType: (*CubeHostImageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListImages",
			Handler:    _CubeHostImageService_ListImages_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReverseStreamForwardImage",
			Handler:       _CubeHostImageService_ReverseStreamForwardImage_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/services/cubehost/v1/hostimage.proto",
}

const (
	CubeVMImageService_ListImages_FullMethodName = "/cubelet.services.cubebox.hostimage.v1.CubeVMImageService/ListImages"
	CubeVMImageService_PullImage_FullMethodName  = "/cubelet.services.cubebox.hostimage.v1.CubeVMImageService/PullImage"
	CubeVMImageService_Mount_FullMethodName      = "/cubelet.services.cubebox.hostimage.v1.CubeVMImageService/Mount"
)

type CubeVMImageServiceClient interface {
	ListImages(ctx context.Context, in *ListImagesRequest, opts ...grpc.CallOption) (*ListImagesResponse, error)

	PullImage(ctx context.Context, in *ForwardImageRequest, opts ...grpc.CallOption) (*ForwardImageResponse, error)

	Mount(ctx context.Context, in *MountImageRequest, opts ...grpc.CallOption) (*MountImageRequest, error)
}

type cubeVMImageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCubeVMImageServiceClient(cc grpc.ClientConnInterface) CubeVMImageServiceClient {
	return &cubeVMImageServiceClient{cc}
}

func (c *cubeVMImageServiceClient) ListImages(ctx context.Context, in *ListImagesRequest, opts ...grpc.CallOption) (*ListImagesResponse, error) {
	out := new(ListImagesResponse)
	err := c.cc.Invoke(ctx, CubeVMImageService_ListImages_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cubeVMImageServiceClient) PullImage(ctx context.Context, in *ForwardImageRequest, opts ...grpc.CallOption) (*ForwardImageResponse, error) {
	out := new(ForwardImageResponse)
	err := c.cc.Invoke(ctx, CubeVMImageService_PullImage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cubeVMImageServiceClient) Mount(ctx context.Context, in *MountImageRequest, opts ...grpc.CallOption) (*MountImageRequest, error) {
	out := new(MountImageRequest)
	err := c.cc.Invoke(ctx, CubeVMImageService_Mount_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type CubeVMImageServiceServer interface {
	ListImages(context.Context, *ListImagesRequest) (*ListImagesResponse, error)

	PullImage(context.Context, *ForwardImageRequest) (*ForwardImageResponse, error)

	Mount(context.Context, *MountImageRequest) (*MountImageRequest, error)
	mustEmbedUnimplementedCubeVMImageServiceServer()
}

type UnimplementedCubeVMImageServiceServer struct {
}

func (UnimplementedCubeVMImageServiceServer) ListImages(context.Context, *ListImagesRequest) (*ListImagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListImages not implemented")
}
func (UnimplementedCubeVMImageServiceServer) PullImage(context.Context, *ForwardImageRequest) (*ForwardImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PullImage not implemented")
}
func (UnimplementedCubeVMImageServiceServer) Mount(context.Context, *MountImageRequest) (*MountImageRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Mount not implemented")
}
func (UnimplementedCubeVMImageServiceServer) mustEmbedUnimplementedCubeVMImageServiceServer() {}

type UnsafeCubeVMImageServiceServer interface {
	mustEmbedUnimplementedCubeVMImageServiceServer()
}

func RegisterCubeVMImageServiceServer(s grpc.ServiceRegistrar, srv CubeVMImageServiceServer) {
	s.RegisterService(&CubeVMImageService_ServiceDesc, srv)
}

func _CubeVMImageService_ListImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CubeVMImageServiceServer).ListImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CubeVMImageService_ListImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CubeVMImageServiceServer).ListImages(ctx, req.(*ListImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CubeVMImageService_PullImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CubeVMImageServiceServer).PullImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CubeVMImageService_PullImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CubeVMImageServiceServer).PullImage(ctx, req.(*ForwardImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CubeVMImageService_Mount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MountImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CubeVMImageServiceServer).Mount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CubeVMImageService_Mount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CubeVMImageServiceServer).Mount(ctx, req.(*MountImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var CubeVMImageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cubelet.services.cubebox.hostimage.v1.CubeVMImageService",
	HandlerType: (*CubeVMImageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListImages",
			Handler:    _CubeVMImageService_ListImages_Handler,
		},
		{
			MethodName: "PullImage",
			Handler:    _CubeVMImageService_PullImage_Handler,
		},
		{
			MethodName: "Mount",
			Handler:    _CubeVMImageService_Mount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/services/cubehost/v1/hostimage.proto",
}
