// Copyright (c) 2024 Tencent Inc.
// SPDX-License-Identifier: Apache-2.0
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: api/services/multimetadb/v1/multimeta_db.proto

package multimetadb

import (
	v1 "github.com/tencentcloud/CubeSandbox/Cubelet/api/services/errorcode/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// bucket define for boltdb
type BucketDefine struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// bucket 的名字
	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsNamespace bool   `protobuf:"varint,2,opt,name=is_namespace,json=isNamespace,proto3" json:"is_namespace,omitempty"`
	// 当使用独立db时，需要指定db的名字。例如cgroup插件使用了独立db
	DbName string `protobuf:"bytes,3,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	// 对该bucket的描述
	Describe      string `protobuf:"bytes,4,opt,name=describe,proto3" json:"describe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BucketDefine) Reset() {
	*x = BucketDefine{}
	mi := &file_api_services_multimetadb_v1_multimeta_db_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BucketDefine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketDefine) ProtoMessage() {}

func (x *BucketDefine) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_multimetadb_v1_multimeta_db_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketDefine.ProtoReflect.Descriptor instead.
func (*BucketDefine) Descriptor() ([]byte, []int) {
	return file_api_services_multimetadb_v1_multimeta_db_proto_rawDescGZIP(), []int{0}
}

func (x *BucketDefine) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BucketDefine) GetIsNamespace() bool {
	if x != nil {
		return x.IsNamespace
	}
	return false
}

func (x *BucketDefine) GetDbName() string {
	if x != nil {
		return x.DbName
	}
	return ""
}

func (x *BucketDefine) GetDescribe() string {
	if x != nil {
		return x.Describe
	}
	return ""
}

type CommonRequestHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestID     string                 `protobuf:"bytes,1,opt,name=requestID,proto3" json:"requestID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonRequestHeader) Reset() {
	*x = CommonRequestHeader{}
	mi := &file_api_services_multimetadb_v1_multimeta_db_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonRequestHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonRequestHeader) ProtoMessage() {}

func (x *CommonRequestHeader) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_multimetadb_v1_multimeta_db_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonRequestHeader.ProtoReflect.Descriptor instead.
func (*CommonRequestHeader) Descriptor() ([]byte, []int) {
	return file_api_services_multimetadb_v1_multimeta_db_proto_rawDescGZIP(), []int{1}
}

func (x *CommonRequestHeader) GetRequestID() string {
	if x != nil {
		return x.RequestID
	}
	return ""
}

type CommonResponseHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestID     string                 `protobuf:"bytes,1,opt,name=requestID,proto3" json:"requestID,omitempty"`
	Code          v1.ErrorCode           `protobuf:"varint,2,opt,name=code,proto3,enum=cubelet.services.errorcode.v1.ErrorCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonResponseHeader) Reset() {
	*x = CommonResponseHeader{}
	mi := &file_api_services_multimetadb_v1_multimeta_db_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonResponseHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResponseHeader) ProtoMessage() {}

func (x *CommonResponseHeader) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_multimetadb_v1_multimeta_db_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResponseHeader.ProtoReflect.Descriptor instead.
func (*CommonResponseHeader) Descriptor() ([]byte, []int) {
	return file_api_services_multimetadb_v1_multimeta_db_proto_rawDescGZIP(), []int{2}
}

func (x *CommonResponseHeader) GetRequestID() string {
	if x != nil {
		return x.RequestID
	}
	return ""
}

func (x *CommonResponseHeader) GetCode() v1.ErrorCode {
	if x != nil {
		return x.Code
	}
	return v1.ErrorCode(0)
}

func (x *CommonResponseHeader) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetBucketDefinesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *CommonResponseHeader  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	BucketDefines []*BucketDefine        `protobuf:"bytes,2,rep,name=bucket_defines,json=bucketDefines,proto3" json:"bucket_defines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBucketDefinesResponse) Reset() {
	*x = GetBucketDefinesResponse{}
	mi := &file_api_services_multimetadb_v1_multimeta_db_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBucketDefinesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBucketDefinesResponse) ProtoMessage() {}

func (x *GetBucketDefinesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_multimetadb_v1_multimeta_db_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBucketDefinesResponse.ProtoReflect.Descriptor instead.
func (*GetBucketDefinesResponse) Descriptor() ([]byte, []int) {
	return file_api_services_multimetadb_v1_multimeta_db_proto_rawDescGZIP(), []int{3}
}

func (x *GetBucketDefinesResponse) GetHeader() *CommonResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetBucketDefinesResponse) GetBucketDefines() []*BucketDefine {
	if x != nil {
		return x.BucketDefines
	}
	return nil
}

type GetDataRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Header *CommonRequestHeader   `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// bucket 的定义，可能如 erofs {namespace} 这种二级定义
	Buckets []string `protobuf:"bytes,2,rep,name=buckets,proto3" json:"buckets,omitempty"`
	// 数据的key
	Key string `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	// 当使用独立db时，需要指定db的名字。例如cgroup插件使用了独立db
	DbName        string `protobuf:"bytes,4,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDataRequest) Reset() {
	*x = GetDataRequest{}
	mi := &file_api_services_multimetadb_v1_multimeta_db_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataRequest) ProtoMessage() {}

func (x *GetDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_multimetadb_v1_multimeta_db_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataRequest.ProtoReflect.Descriptor instead.
func (*GetDataRequest) Descriptor() ([]byte, []int) {
	return file_api_services_multimetadb_v1_multimeta_db_proto_rawDescGZIP(), []int{4}
}

func (x *GetDataRequest) GetHeader() *CommonRequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetDataRequest) GetBuckets() []string {
	if x != nil {
		return x.Buckets
	}
	return nil
}

func (x *GetDataRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetDataRequest) GetDbName() string {
	if x != nil {
		return x.DbName
	}
	return ""
}

type DbData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// key of this data
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// bucket 的定义，可能如 erofs {namespace} 这种二级定义
	Buckets []string `protobuf:"bytes,2,rep,name=buckets,proto3" json:"buckets,omitempty"`
	// 数据的value
	Value         []byte `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DbData) Reset() {
	*x = DbData{}
	mi := &file_api_services_multimetadb_v1_multimeta_db_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DbData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DbData) ProtoMessage() {}

func (x *DbData) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_multimetadb_v1_multimeta_db_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DbData.ProtoReflect.Descriptor instead.
func (*DbData) Descriptor() ([]byte, []int) {
	return file_api_services_multimetadb_v1_multimeta_db_proto_rawDescGZIP(), []int{5}
}

func (x *DbData) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DbData) GetBuckets() []string {
	if x != nil {
		return x.Buckets
	}
	return nil
}

func (x *DbData) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_api_services_multimetadb_v1_multimeta_db_proto protoreflect.FileDescriptor

const file_api_services_multimetadb_v1_multimeta_db_proto_rawDesc = "" +
	"\n" +
	".api/services/multimetadb/v1/multimeta_db.proto\x12\x1fcubelet.services.multimetadb.v1\x1a)api/services/errorcode/v1/errorcode.proto\"z\n" +
	"\fBucketDefine\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fis_namespace\x18\x02 \x01(\bR\visNamespace\x12\x17\n" +
	"\adb_name\x18\x03 \x01(\tR\x06dbName\x12\x1a\n" +
	"\bdescribe\x18\x04 \x01(\tR\bdescribe\"3\n" +
	"\x13CommonRequestHeader\x12\x1c\n" +
	"\trequestID\x18\x01 \x01(\tR\trequestID\"\x8c\x01\n" +
	"\x14CommonResponseHeader\x12\x1c\n" +
	"\trequestID\x18\x01 \x01(\tR\trequestID\x12<\n" +
	"\x04code\x18\x02 \x01(\x0e2(.cubelet.services.errorcode.v1.ErrorCodeR\x04code\x12\x18\n" +
	"\aMessage\x18\x03 \x01(\tR\aMessage\"\xbf\x01\n" +
	"\x18GetBucketDefinesResponse\x12M\n" +
	"\x06header\x18\x01 \x01(\v25.cubelet.services.multimetadb.v1.CommonResponseHeaderR\x06header\x12T\n" +
	"\x0ebucket_defines\x18\x02 \x03(\v2-.cubelet.services.multimetadb.v1.BucketDefineR\rbucketDefines\"\xa3\x01\n" +
	"\x0eGetDataRequest\x12L\n" +
	"\x06header\x18\x01 \x01(\v24.cubelet.services.multimetadb.v1.CommonRequestHeaderR\x06header\x12\x18\n" +
	"\abuckets\x18\x02 \x03(\tR\abuckets\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x17\n" +
	"\adb_name\x18\x04 \x01(\tR\x06dbName\"J\n" +
	"\x06DbData\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x18\n" +
	"\abuckets\x18\x02 \x03(\tR\abuckets\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value2\x8a\x02\n" +
	"\x11MultiMetaDBServer\x12\x85\x01\n" +
	"\x10GetBucketDefines\x124.cubelet.services.multimetadb.v1.CommonRequestHeader\x1a9.cubelet.services.multimetadb.v1.GetBucketDefinesResponse\"\x00\x12m\n" +
	"\rGetStreamData\x12/.cubelet.services.multimetadb.v1.GetDataRequest\x1a'.cubelet.services.multimetadb.v1.DbData\"\x000\x01BUZSgithub.com/tencentcloud/CubeSandbox/Cubelet/api/services/multimetadb/v1;multimetadbb\x06proto3"

var (
	file_api_services_multimetadb_v1_multimeta_db_proto_rawDescOnce sync.Once
	file_api_services_multimetadb_v1_multimeta_db_proto_rawDescData []byte
)

func file_api_services_multimetadb_v1_multimeta_db_proto_rawDescGZIP() []byte {
	file_api_services_multimetadb_v1_multimeta_db_proto_rawDescOnce.Do(func() {
		file_api_services_multimetadb_v1_multimeta_db_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_services_multimetadb_v1_multimeta_db_proto_rawDesc), len(file_api_services_multimetadb_v1_multimeta_db_proto_rawDesc)))
	})
	return file_api_services_multimetadb_v1_multimeta_db_proto_rawDescData
}

var file_api_services_multimetadb_v1_multimeta_db_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_services_multimetadb_v1_multimeta_db_proto_goTypes = []any{
	(*BucketDefine)(nil),             // 0: cubelet.services.multimetadb.v1.BucketDefine
	(*CommonRequestHeader)(nil),      // 1: cubelet.services.multimetadb.v1.CommonRequestHeader
	(*CommonResponseHeader)(nil),     // 2: cubelet.services.multimetadb.v1.CommonResponseHeader
	(*GetBucketDefinesResponse)(nil), // 3: cubelet.services.multimetadb.v1.GetBucketDefinesResponse
	(*GetDataRequest)(nil),           // 4: cubelet.services.multimetadb.v1.GetDataRequest
	(*DbData)(nil),                   // 5: cubelet.services.multimetadb.v1.DbData
	(v1.ErrorCode)(0),                // 6: cubelet.services.errorcode.v1.ErrorCode
}
var file_api_services_multimetadb_v1_multimeta_db_proto_depIdxs = []int32{
	6, // 0: cubelet.services.multimetadb.v1.CommonResponseHeader.code:type_name -> cubelet.services.errorcode.v1.ErrorCode
	2, // 1: cubelet.services.multimetadb.v1.GetBucketDefinesResponse.header:type_name -> cubelet.services.multimetadb.v1.CommonResponseHeader
	0, // 2: cubelet.services.multimetadb.v1.GetBucketDefinesResponse.bucket_defines:type_name -> cubelet.services.multimetadb.v1.BucketDefine
	1, // 3: cubelet.services.multimetadb.v1.GetDataRequest.header:type_name -> cubelet.services.multimetadb.v1.CommonRequestHeader
	1, // 4: cubelet.services.multimetadb.v1.MultiMetaDBServer.GetBucketDefines:input_type -> cubelet.services.multimetadb.v1.CommonRequestHeader
	4, // 5: cubelet.services.multimetadb.v1.MultiMetaDBServer.GetStreamData:input_type -> cubelet.services.multimetadb.v1.GetDataRequest
	3, // 6: cubelet.services.multimetadb.v1.MultiMetaDBServer.GetBucketDefines:output_type -> cubelet.services.multimetadb.v1.GetBucketDefinesResponse
	5, // 7: cubelet.services.multimetadb.v1.MultiMetaDBServer.GetStreamData:output_type -> cubelet.services.multimetadb.v1.DbData
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_services_multimetadb_v1_multimeta_db_proto_init() }
func file_api_services_multimetadb_v1_multimeta_db_proto_init() {
	if File_api_services_multimetadb_v1_multimeta_db_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_services_multimetadb_v1_multimeta_db_proto_rawDesc), len(file_api_services_multimetadb_v1_multimeta_db_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_services_multimetadb_v1_multimeta_db_proto_goTypes,
		DependencyIndexes: file_api_services_multimetadb_v1_multimeta_db_proto_depIdxs,
		MessageInfos:      file_api_services_multimetadb_v1_multimeta_db_proto_msgTypes,
	}.Build()
	File_api_services_multimetadb_v1_multimeta_db_proto = out.File
	file_api_services_multimetadb_v1_multimeta_db_proto_goTypes = nil
	file_api_services_multimetadb_v1_multimeta_db_proto_depIdxs = nil
}
