// Copyright (c) 2024 Tencent Inc.
// SPDX-License-Identifier: Apache-2.0
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.3
// source: api/services/multimetadb/v1/multimeta_db.proto

package multimetadb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MultiMetaDBServer_GetBucketDefines_FullMethodName = "/cubelet.services.multimetadb.v1.MultiMetaDBServer/GetBucketDefines"
	MultiMetaDBServer_GetStreamData_FullMethodName    = "/cubelet.services.multimetadb.v1.MultiMetaDBServer/GetStreamData"
)

// MultiMetaDBServerClient is the client API for MultiMetaDBServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service for machine level operations.
type MultiMetaDBServerClient interface {
	GetBucketDefines(ctx context.Context, in *CommonRequestHeader, opts ...grpc.CallOption) (*GetBucketDefinesResponse, error)
	// 使用流式接口，批量查询db中的数据
	GetStreamData(ctx context.Context, in *GetDataRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DbData], error)
}

type multiMetaDBServerClient struct {
	cc grpc.ClientConnInterface
}

func NewMultiMetaDBServerClient(cc grpc.ClientConnInterface) MultiMetaDBServerClient {
	return &multiMetaDBServerClient{cc}
}

func (c *multiMetaDBServerClient) GetBucketDefines(ctx context.Context, in *CommonRequestHeader, opts ...grpc.CallOption) (*GetBucketDefinesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBucketDefinesResponse)
	err := c.cc.Invoke(ctx, MultiMetaDBServer_GetBucketDefines_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multiMetaDBServerClient) GetStreamData(ctx context.Context, in *GetDataRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DbData], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MultiMetaDBServer_ServiceDesc.Streams[0], MultiMetaDBServer_GetStreamData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetDataRequest, DbData]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MultiMetaDBServer_GetStreamDataClient = grpc.ServerStreamingClient[DbData]

// MultiMetaDBServerServer is the server API for MultiMetaDBServer service.
// All implementations must embed UnimplementedMultiMetaDBServerServer
// for forward compatibility.
//
// Service for machine level operations.
type MultiMetaDBServerServer interface {
	GetBucketDefines(context.Context, *CommonRequestHeader) (*GetBucketDefinesResponse, error)
	// 使用流式接口，批量查询db中的数据
	GetStreamData(*GetDataRequest, grpc.ServerStreamingServer[DbData]) error
	mustEmbedUnimplementedMultiMetaDBServerServer()
}

// UnimplementedMultiMetaDBServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMultiMetaDBServerServer struct{}

func (UnimplementedMultiMetaDBServerServer) GetBucketDefines(context.Context, *CommonRequestHeader) (*GetBucketDefinesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBucketDefines not implemented")
}
func (UnimplementedMultiMetaDBServerServer) GetStreamData(*GetDataRequest, grpc.ServerStreamingServer[DbData]) error {
	return status.Error(codes.Unimplemented, "method GetStreamData not implemented")
}
func (UnimplementedMultiMetaDBServerServer) mustEmbedUnimplementedMultiMetaDBServerServer() {}
func (UnimplementedMultiMetaDBServerServer) testEmbeddedByValue()                           {}

// UnsafeMultiMetaDBServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MultiMetaDBServerServer will
// result in compilation errors.
type UnsafeMultiMetaDBServerServer interface {
	mustEmbedUnimplementedMultiMetaDBServerServer()
}

func RegisterMultiMetaDBServerServer(s grpc.ServiceRegistrar, srv MultiMetaDBServerServer) {
	// If the following call panics, it indicates UnimplementedMultiMetaDBServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MultiMetaDBServer_ServiceDesc, srv)
}

func _MultiMetaDBServer_GetBucketDefines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommonRequestHeader)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultiMetaDBServerServer).GetBucketDefines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultiMetaDBServer_GetBucketDefines_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultiMetaDBServerServer).GetBucketDefines(ctx, req.(*CommonRequestHeader))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultiMetaDBServer_GetStreamData_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetDataRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MultiMetaDBServerServer).GetStreamData(m, &grpc.GenericServerStream[GetDataRequest, DbData]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MultiMetaDBServer_GetStreamDataServer = grpc.ServerStreamingServer[DbData]

// MultiMetaDBServer_ServiceDesc is the grpc.ServiceDesc for MultiMetaDBServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MultiMetaDBServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cubelet.services.multimetadb.v1.MultiMetaDBServer",
	HandlerType: (*MultiMetaDBServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBucketDefines",
			Handler:    _MultiMetaDBServer_GetBucketDefines_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetStreamData",
			Handler:       _MultiMetaDBServer_GetStreamData_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/services/multimetadb/v1/multimeta_db.proto",
}
