{{- if and .Values.controlPlane.enabled .Values.controlPlane.master.enabled }}
{{- $conf := tpl (.Files.Get "files/cube-master/conf.yaml") . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cube.masterConfigSecretName" . }}
  labels:
    {{- include "cube.labels" . | nindent 4 }}
    app.kubernetes.io/component: master
type: Opaque
stringData:
  conf.yaml: |-
{{ $conf | nindent 4 }}
{{- end }}
