{{- if and .Values.cubeNode.enabled .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cube.nodeServiceAccountName" . }}
  labels:
    {{- include "cube.labels" . | nindent 4 }}
    app.kubernetes.io/component: cube-node
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
{{- end }}
