[package]
name = "uvm-uffd-core"
version = "0.1.0"
edition = "2021"

[features]
default = ["overlaybd"]
overlaybd = ["dep:overlaybd"]

[dependencies]
storage-util = { path = "../util" }
overlaybd = { path = "../overlaybd", optional = true }
anyhow = "1.0"
async-trait = "0.1"
bytes = "1"
dashmap = "6"
libc = "0.2"
nix = { version = "0.30", features = ["socket", "uio", "process"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["net", "rt", "sync", "macros"] }
tracing = "0.1"
userfaultfd = "0.9"
uuid = { version = "1", features = ["v4"] }
