// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: api/proto/scheduler.proto

package schedulerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Scheduler_Schedule_FullMethodName           = "/scheduler.v1.Scheduler/Schedule"
	Scheduler_ListNodes_FullMethodName          = "/scheduler.v1.Scheduler/ListNodes"
	Scheduler_LookupNode_FullMethodName         = "/scheduler.v1.Scheduler/LookupNode"
	Scheduler_RecordAssignment_FullMethodName   = "/scheduler.v1.Scheduler/RecordAssignment"
	Scheduler_Heartbeat_FullMethodName          = "/scheduler.v1.Scheduler/Heartbeat"
	Scheduler_ReportSandboxEvent_FullMethodName = "/scheduler.v1.Scheduler/ReportSandboxEvent"
	Scheduler_ListObservedNodes_FullMethodName  = "/scheduler.v1.Scheduler/ListObservedNodes"
	Scheduler_ListP2PPeers_FullMethodName       = "/scheduler.v1.Scheduler/ListP2pPeers"
	Scheduler_RecordP2PArtifact_FullMethodName  = "/scheduler.v1.Scheduler/RecordP2pArtifact"
	Scheduler_ForgetP2PArtifact_FullMethodName  = "/scheduler.v1.Scheduler/ForgetP2pArtifact"
	Scheduler_LookupP2PArtifact_FullMethodName  = "/scheduler.v1.Scheduler/LookupP2pArtifact"
	Scheduler_GetNode_FullMethodName            = "/scheduler.v1.Scheduler/GetNode"
	Scheduler_UnregisterNode_FullMethodName     = "/scheduler.v1.Scheduler/UnregisterNode"
)

// SchedulerClient is the client API for Scheduler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SchedulerClient interface {
	Schedule(ctx context.Context, in *ScheduleRequest, opts ...grpc.CallOption) (*ScheduleResponse, error)
	ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error)
	LookupNode(ctx context.Context, in *LookupNodeRequest, opts ...grpc.CallOption) (*LookupNodeResponse, error)
	RecordAssignment(ctx context.Context, in *RecordAssignmentRequest, opts ...grpc.CallOption) (*RecordAssignmentResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	ReportSandboxEvent(ctx context.Context, in *ReportSandboxEventRequest, opts ...grpc.CallOption) (*ReportSandboxEventResponse, error)
	ListObservedNodes(ctx context.Context, in *ListObservedNodesRequest, opts ...grpc.CallOption) (*ListObservedNodesResponse, error)
	ListP2PPeers(ctx context.Context, in *ListP2PPeersRequest, opts ...grpc.CallOption) (*ListP2PPeersResponse, error)
	RecordP2PArtifact(ctx context.Context, in *RecordP2PArtifactRequest, opts ...grpc.CallOption) (*RecordP2PArtifactResponse, error)
	ForgetP2PArtifact(ctx context.Context, in *ForgetP2PArtifactRequest, opts ...grpc.CallOption) (*ForgetP2PArtifactResponse, error)
	LookupP2PArtifact(ctx context.Context, in *LookupP2PArtifactRequest, opts ...grpc.CallOption) (*LookupP2PArtifactResponse, error)
	GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error)
	UnregisterNode(ctx context.Context, in *UnregisterNodeRequest, opts ...grpc.CallOption) (*UnregisterNodeResponse, error)
}

type schedulerClient struct {
	cc grpc.ClientConnInterface
}

func NewSchedulerClient(cc grpc.ClientConnInterface) SchedulerClient {
	return &schedulerClient{cc}
}

func (c *schedulerClient) Schedule(ctx context.Context, in *ScheduleRequest, opts ...grpc.CallOption) (*ScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScheduleResponse)
	err := c.cc.Invoke(ctx, Scheduler_Schedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNodesResponse)
	err := c.cc.Invoke(ctx, Scheduler_ListNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) LookupNode(ctx context.Context, in *LookupNodeRequest, opts ...grpc.CallOption) (*LookupNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LookupNodeResponse)
	err := c.cc.Invoke(ctx, Scheduler_LookupNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) RecordAssignment(ctx context.Context, in *RecordAssignmentRequest, opts ...grpc.CallOption) (*RecordAssignmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordAssignmentResponse)
	err := c.cc.Invoke(ctx, Scheduler_RecordAssignment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, Scheduler_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) ReportSandboxEvent(ctx context.Context, in *ReportSandboxEventRequest, opts ...grpc.CallOption) (*ReportSandboxEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportSandboxEventResponse)
	err := c.cc.Invoke(ctx, Scheduler_ReportSandboxEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) ListObservedNodes(ctx context.Context, in *ListObservedNodesRequest, opts ...grpc.CallOption) (*ListObservedNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListObservedNodesResponse)
	err := c.cc.Invoke(ctx, Scheduler_ListObservedNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) ListP2PPeers(ctx context.Context, in *ListP2PPeersRequest, opts ...grpc.CallOption) (*ListP2PPeersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListP2PPeersResponse)
	err := c.cc.Invoke(ctx, Scheduler_ListP2PPeers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) RecordP2PArtifact(ctx context.Context, in *RecordP2PArtifactRequest, opts ...grpc.CallOption) (*RecordP2PArtifactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordP2PArtifactResponse)
	err := c.cc.Invoke(ctx, Scheduler_RecordP2PArtifact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) ForgetP2PArtifact(ctx context.Context, in *ForgetP2PArtifactRequest, opts ...grpc.CallOption) (*ForgetP2PArtifactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForgetP2PArtifactResponse)
	err := c.cc.Invoke(ctx, Scheduler_ForgetP2PArtifact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) LookupP2PArtifact(ctx context.Context, in *LookupP2PArtifactRequest, opts ...grpc.CallOption) (*LookupP2PArtifactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LookupP2PArtifactResponse)
	err := c.cc.Invoke(ctx, Scheduler_LookupP2PArtifact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeResponse)
	err := c.cc.Invoke(ctx, Scheduler_GetNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) UnregisterNode(ctx context.Context, in *UnregisterNodeRequest, opts ...grpc.CallOption) (*UnregisterNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnregisterNodeResponse)
	err := c.cc.Invoke(ctx, Scheduler_UnregisterNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SchedulerServer is the server API for Scheduler service.
// All implementations must embed UnimplementedSchedulerServer
// for forward compatibility.
type SchedulerServer interface {
	Schedule(context.Context, *ScheduleRequest) (*ScheduleResponse, error)
	ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error)
	LookupNode(context.Context, *LookupNodeRequest) (*LookupNodeResponse, error)
	RecordAssignment(context.Context, *RecordAssignmentRequest) (*RecordAssignmentResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	ReportSandboxEvent(context.Context, *ReportSandboxEventRequest) (*ReportSandboxEventResponse, error)
	ListObservedNodes(context.Context, *ListObservedNodesRequest) (*ListObservedNodesResponse, error)
	ListP2PPeers(context.Context, *ListP2PPeersRequest) (*ListP2PPeersResponse, error)
	RecordP2PArtifact(context.Context, *RecordP2PArtifactRequest) (*RecordP2PArtifactResponse, error)
	ForgetP2PArtifact(context.Context, *ForgetP2PArtifactRequest) (*ForgetP2PArtifactResponse, error)
	LookupP2PArtifact(context.Context, *LookupP2PArtifactRequest) (*LookupP2PArtifactResponse, error)
	GetNode(context.Context, *GetNodeRequest) (*GetNodeResponse, error)
	UnregisterNode(context.Context, *UnregisterNodeRequest) (*UnregisterNodeResponse, error)
	mustEmbedUnimplementedSchedulerServer()
}

// UnimplementedSchedulerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSchedulerServer struct{}

func (UnimplementedSchedulerServer) Schedule(context.Context, *ScheduleRequest) (*ScheduleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Schedule not implemented")
}
func (UnimplementedSchedulerServer) ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNodes not implemented")
}
func (UnimplementedSchedulerServer) LookupNode(context.Context, *LookupNodeRequest) (*LookupNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LookupNode not implemented")
}
func (UnimplementedSchedulerServer) RecordAssignment(context.Context, *RecordAssignmentRequest) (*RecordAssignmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordAssignment not implemented")
}
func (UnimplementedSchedulerServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedSchedulerServer) ReportSandboxEvent(context.Context, *ReportSandboxEventRequest) (*ReportSandboxEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportSandboxEvent not implemented")
}
func (UnimplementedSchedulerServer) ListObservedNodes(context.Context, *ListObservedNodesRequest) (*ListObservedNodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListObservedNodes not implemented")
}
func (UnimplementedSchedulerServer) ListP2PPeers(context.Context, *ListP2PPeersRequest) (*ListP2PPeersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListP2PPeers not implemented")
}
func (UnimplementedSchedulerServer) RecordP2PArtifact(context.Context, *RecordP2PArtifactRequest) (*RecordP2PArtifactResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordP2PArtifact not implemented")
}
func (UnimplementedSchedulerServer) ForgetP2PArtifact(context.Context, *ForgetP2PArtifactRequest) (*ForgetP2PArtifactResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForgetP2PArtifact not implemented")
}
func (UnimplementedSchedulerServer) LookupP2PArtifact(context.Context, *LookupP2PArtifactRequest) (*LookupP2PArtifactResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LookupP2PArtifact not implemented")
}
func (UnimplementedSchedulerServer) GetNode(context.Context, *GetNodeRequest) (*GetNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNode not implemented")
}
func (UnimplementedSchedulerServer) UnregisterNode(context.Context, *UnregisterNodeRequest) (*UnregisterNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnregisterNode not implemented")
}
func (UnimplementedSchedulerServer) mustEmbedUnimplementedSchedulerServer() {}
func (UnimplementedSchedulerServer) testEmbeddedByValue()                   {}

// UnsafeSchedulerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SchedulerServer will
// result in compilation errors.
type UnsafeSchedulerServer interface {
	mustEmbedUnimplementedSchedulerServer()
}

func RegisterSchedulerServer(s grpc.ServiceRegistrar, srv SchedulerServer) {
	// If the following call panics, it indicates UnimplementedSchedulerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Scheduler_ServiceDesc, srv)
}

func _Scheduler_Schedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).Schedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Scheduler_Schedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).Schedule(ctx, req.(*ScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_ListNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).ListNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Scheduler_ListNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).ListNodes(ctx, req.(*ListNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_LookupNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).LookupNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Scheduler_LookupNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).LookupNode(ctx, req.(*LookupNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_RecordAssignment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordAssignmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).RecordAssignment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Scheduler_RecordAssignment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).RecordAssignment(ctx, req.(*RecordAssignmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Scheduler_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_ReportSandboxEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportSandboxEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).ReportSandboxEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Scheduler_ReportSandboxEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).ReportSandboxEvent(ctx, req.(*ReportSandboxEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_ListObservedNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListObservedNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).ListObservedNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Scheduler_ListObservedNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).ListObservedNodes(ctx, req.(*ListObservedNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_ListP2PPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListP2PPeersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).ListP2PPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Scheduler_ListP2PPeers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).ListP2PPeers(ctx, req.(*ListP2PPeersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_RecordP2PArtifact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordP2PArtifactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).RecordP2PArtifact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Scheduler_RecordP2PArtifact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).RecordP2PArtifact(ctx, req.(*RecordP2PArtifactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_ForgetP2PArtifact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForgetP2PArtifactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).ForgetP2PArtifact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Scheduler_ForgetP2PArtifact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).ForgetP2PArtifact(ctx, req.(*ForgetP2PArtifactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_LookupP2PArtifact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupP2PArtifactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).LookupP2PArtifact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Scheduler_LookupP2PArtifact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).LookupP2PArtifact(ctx, req.(*LookupP2PArtifactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Scheduler_GetNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).GetNode(ctx, req.(*GetNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_UnregisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).UnregisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Scheduler_UnregisterNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).UnregisterNode(ctx, req.(*UnregisterNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Scheduler_ServiceDesc is the grpc.ServiceDesc for Scheduler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Scheduler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scheduler.v1.Scheduler",
	HandlerType: (*SchedulerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Schedule",
			Handler:    _Scheduler_Schedule_Handler,
		},
		{
			MethodName: "ListNodes",
			Handler:    _Scheduler_ListNodes_Handler,
		},
		{
			MethodName: "LookupNode",
			Handler:    _Scheduler_LookupNode_Handler,
		},
		{
			MethodName: "RecordAssignment",
			Handler:    _Scheduler_RecordAssignment_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _Scheduler_Heartbeat_Handler,
		},
		{
			MethodName: "ReportSandboxEvent",
			Handler:    _Scheduler_ReportSandboxEvent_Handler,
		},
		{
			MethodName: "ListObservedNodes",
			Handler:    _Scheduler_ListObservedNodes_Handler,
		},
		{
			MethodName: "ListP2pPeers",
			Handler:    _Scheduler_ListP2PPeers_Handler,
		},
		{
			MethodName: "RecordP2pArtifact",
			Handler:    _Scheduler_RecordP2PArtifact_Handler,
		},
		{
			MethodName: "ForgetP2pArtifact",
			Handler:    _Scheduler_ForgetP2PArtifact_Handler,
		},
		{
			MethodName: "LookupP2pArtifact",
			Handler:    _Scheduler_LookupP2PArtifact_Handler,
		},
		{
			MethodName: "GetNode",
			Handler:    _Scheduler_GetNode_Handler,
		},
		{
			MethodName: "UnregisterNode",
			Handler:    _Scheduler_UnregisterNode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/scheduler.proto",
}
