// Copyright (c) 2024 Tencent Inc.
// SPDX-License-Identifier: Apache-2.0
//

package ext4image

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"os"
	"path/filepath"
	"strings"
	"testing"

	cubeimages "github.com/tencentcloud/CubeSandbox/Cubelet/api/services/images/v1"
	"github.com/tencentcloud/CubeSandbox/Cubelet/pkg/constants"
	"github.com/tencentcloud/CubeSandbox/Cubelet/pkg/container/pmem"
)

func writeTestFile(t *testing.T, path string, content []byte) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("MkdirAll %s error=%v", path, err)
	}
	if err := os.WriteFile(path, content, 0o644); err != nil {
		t.Fatalf("WriteFile %s error=%v", path, err)
	}
}

func writeSharedKernelFile(t *testing.T, content []byte) {
	t.Helper()
	writeTestFile(t, pmem.GetSharedKernelFilePath(), content)
}

func writeRawImageFile(t *testing.T, instanceType, imageRef string, content []byte) {
	t.Helper()
	writeTestFile(t, pmem.GetRawImageFilePath(instanceType, imageRef), content)
}

func writeRawKernelFile(t *testing.T, instanceType, imageRef string, content []byte) {
	t.Helper()
	writeTestFile(t, pmem.GetRawKernelFilePath(instanceType, imageRef), content)
}

func TestRefreshArtifactRuntimeFilesRefreshesKernelWhenSharedKernelChanges(t *testing.T) {
	baseDir := t.TempDir()
	pmem.Init(baseDir)

	kernelV1 := bytes.Repeat([]byte("a"), 2048)
	writeSharedKernelFile(t, kernelV1)

	if err := RefreshArtifactRuntimeFiles(context.Background(), "cubebox", "artifact-1"); err != nil {
		t.Fatalf("RefreshArtifactRuntimeFiles error=%v", err)
	}

	targetKernelPath := pmem.GetRawKernelFilePath("cubebox", "artifact-1")
	got, err := os.ReadFile(targetKernelPath)
	if err != nil {
		t.Fatalf("ReadFile target kernel error=%v", err)
	}
	if !bytes.Equal(got, kernelV1) {
		t.Fatal("target kernel content mismatch after first copy")
	}
	assertRawKernelVersionMatches(t, "cubebox", "artifact-1", kernelV1)

	kernelV2 := bytes.Repeat([]byte("b"), 4096)
	writeSharedKernelFile(t, kernelV2)
	if err := RefreshArtifactRuntimeFiles(context.Background(), "cubebox", "artifact-1"); err != nil {
		t.Fatalf("RefreshArtifactRuntimeFiles second call error=%v", err)
	}

	got, err = os.ReadFile(targetKernelPath)
	if err != nil {
		t.Fatalf("ReadFile target kernel after second call error=%v", err)
	}
	if !bytes.Equal(got, kernelV2) {
		t.Fatal("target kernel should refresh to latest shared content")
	}
	assertRawKernelVersionMatches(t, "cubebox", "artifact-1", kernelV2)
}

func TestEnsurePmemFilePreservesExistingRuntimeFiles(t *testing.T) {
	baseDir := t.TempDir()
	pmem.Init(baseDir)

	writeSharedKernelFile(t, bytes.Repeat([]byte("s"), 3072))
	writeRawImageFile(t, "cubebox", "artifact-2", bytes.Repeat([]byte("e"), 2048))
	targetKernelPath := pmem.GetRawKernelFilePath("cubebox", "artifact-2")
	oldKernel := bytes.Repeat([]byte("o"), 3072)
	writeRawKernelFile(t, "cubebox", "artifact-2", oldKernel)
	ctx := constants.WithImageSpec(context.Background(), &cubeimages.ImageSpec{
		Annotations: map[string]string{
			constants.MasterAnnotationRootfsArtifactURL:    "http://unused.example/artifact.ext4",
			constants.MasterAnnotationRootfsArtifactSHA256: "deadbeef",
		},
	})

	if err := EnsurePmemFile(ctx, "cubebox", "artifact-2"); err != nil {
		t.Fatalf("EnsurePmemFile error=%v", err)
	}

	got, err := os.ReadFile(targetKernelPath)
	if err != nil {
		t.Fatalf("ReadFile target kernel error=%v", err)
	}
	if !bytes.Equal(got, oldKernel) {
		t.Fatal("target kernel should stay unchanged when file already exists")
	}
	if _, statErr := os.Stat(rawKernelVersionPath("cubebox", "artifact-2")); !os.IsNotExist(statErr) {
		t.Fatalf("existing runtime version should not be required or generated by EnsurePmemFile, statErr=%v", statErr)
	}
}

func TestEnsurePmemFileMaterializesFreshArtifactKernel(t *testing.T) {
	baseDir := t.TempDir()
	pmem.Init(baseDir)

	sharedKernel := bytes.Repeat([]byte("s"), 3072)
	writeSharedKernelFile(t, sharedKernel)
	writeRawImageFile(t, "cubebox", "artifact-3", bytes.Repeat([]byte("e"), 2048))

	if err := EnsurePmemFile(context.Background(), "cubebox", "artifact-3"); err != nil {
		t.Fatalf("EnsurePmemFile error=%v", err)
	}

	got, err := os.ReadFile(pmem.GetRawKernelFilePath("cubebox", "artifact-3"))
	if err != nil {
		t.Fatalf("ReadFile materialized kernel error=%v", err)
	}
	if !bytes.Equal(got, sharedKernel) {
		t.Fatal("materialized kernel should match shared kernel")
	}
	assertRawKernelVersionMatches(t, "cubebox", "artifact-3", sharedKernel)
}

func TestEnsurePmemRootfsDoesNotRequireKernelFile(t *testing.T) {
	baseDir := t.TempDir()
	pmem.Init(baseDir)

	writeRawImageFile(t, "cubebox", "artifact-4", bytes.Repeat([]byte("e"), 2048))

	if err := EnsurePmemRootfs(context.Background(), "cubebox", "artifact-4"); err != nil {
		t.Fatalf("EnsurePmemRootfs error=%v", err)
	}
}

func TestEnsurePmemFileDoesNotRequireCubeImageVersionFile(t *testing.T) {
	baseDir := t.TempDir()
	pmem.Init(baseDir)

	sharedKernel := bytes.Repeat([]byte("s"), 3072)
	writeSharedKernelFile(t, sharedKernel)
	writeRawImageFile(t, "cubebox", "artifact-5", bytes.Repeat([]byte("e"), 2048))

	if err := EnsurePmemFile(context.Background(), "cubebox", "artifact-5"); err != nil {
		t.Fatalf("EnsurePmemFile error=%v", err)
	}

	got, err := os.ReadFile(pmem.GetRawKernelFilePath("cubebox", "artifact-5"))
	if err != nil {
		t.Fatalf("ReadFile materialized kernel error=%v", err)
	}
	if !bytes.Equal(got, sharedKernel) {
		t.Fatal("materialized kernel should match shared kernel")
	}
	assertRawKernelVersionMatches(t, "cubebox", "artifact-5", sharedKernel)
}

func TestEnsureKernelFilePresentRequiresSharedKernel(t *testing.T) {
	baseDir := t.TempDir()
	pmem.Init(baseDir)

	err := ensureKernelFilePresent(context.Background(), "cubebox", "artifact-2")
	if err == nil {
		t.Fatal("ensureKernelFilePresent error=nil, want non-nil")
	}
}

func rawKernelVersionPath(instanceType, imageRef string) string {
	return filepath.Join(filepath.Dir(pmem.GetRawKernelFilePath(instanceType, imageRef)), "version")
}

func kernelVersionForContent(content []byte) string {
	sum := sha256.Sum256(content)
	return "sha256:" + hex.EncodeToString(sum[:])
}

func assertRawKernelVersionMatches(t *testing.T, instanceType, imageRef string, kernel []byte) {
	t.Helper()
	got, err := os.ReadFile(rawKernelVersionPath(instanceType, imageRef))
	if err != nil {
		t.Fatalf("ReadFile kernel version error=%v", err)
	}
	if strings.TrimSpace(string(got)) != kernelVersionForContent(kernel) {
		t.Fatalf("kernel version=%q, want %q", strings.TrimSpace(string(got)), kernelVersionForContent(kernel))
	}
}

func TestDestroyPmemArtifactResolvesSymlinkedBase(t *testing.T) {
	dataDir := t.TempDir()
	realBase := filepath.Join(t.TempDir(), "cubebox_os_image")
	if err := os.MkdirAll(realBase, 0o755); err != nil {
		t.Fatalf("MkdirAll real base error=%v", err)
	}
	if err := os.Symlink(realBase, filepath.Join(dataDir, "cubebox_os_image")); err != nil {
		t.Fatalf("Symlink base error=%v", err)
	}
	pmem.Init(dataDir)

	artifactDir := filepath.Join(realBase, "artifact-6")
	writeTestFile(t, filepath.Join(artifactDir, "artifact-6.ext4"), []byte("rootfs"))

	if err := DestroyPmemArtifact(context.Background(), "cubebox", "artifact-6", nil); err != nil {
		t.Fatalf("DestroyPmemArtifact error=%v", err)
	}
	if _, err := os.Stat(artifactDir); !os.IsNotExist(err) {
		t.Fatalf("artifact dir should be removed, stat err=%v", err)
	}
}

func TestDestroyPmemArtifactUnlinksLeafSymlinkOnly(t *testing.T) {
	dataDir := t.TempDir()
	pmem.Init(dataDir)
	base := pmem.GetPmemBasePath("cubebox")
	if err := os.MkdirAll(base, 0o755); err != nil {
		t.Fatalf("MkdirAll base error=%v", err)
	}
	outside := t.TempDir()
	outsideFile := filepath.Join(outside, "keep.txt")
	if err := os.WriteFile(outsideFile, []byte("keep"), 0o644); err != nil {
		t.Fatalf("WriteFile outside error=%v", err)
	}
	leaf := filepath.Join(base, "artifact-7")
	if err := os.Symlink(outside, leaf); err != nil {
		t.Fatalf("Symlink leaf error=%v", err)
	}

	if err := DestroyPmemArtifact(context.Background(), "cubebox", "artifact-7", nil); err != nil {
		t.Fatalf("DestroyPmemArtifact error=%v", err)
	}
	if _, err := os.Lstat(leaf); !os.IsNotExist(err) {
		t.Fatalf("artifact symlink should be removed, lstat err=%v", err)
	}
	if _, err := os.Stat(outsideFile); err != nil {
		t.Fatalf("outside target should remain, stat err=%v", err)
	}
}

func TestDestroyPmemArtifactMissingBaseIsIdempotent(t *testing.T) {
	dataDir := t.TempDir()
	pmem.Init(dataDir)

	if err := DestroyPmemArtifact(context.Background(), "cubebox", "artifact-8", nil); err != nil {
		t.Fatalf("missing pmem base should be success, got %v", err)
	}
}
