source:
  third_party_source:
    filepath_regex: ["vendor/.*"]
  #test_source:
  #  filepath_regex: [".*/.*_test.go", ".*/examples/.*", ".*/test/.*"]
  auto_generate_source:
    # 自动生成代码文件的正则表达式，若无统一标识格式，可以指定具体目录，样例可参考test_source举例
    filepath_regex: [".*/.*.pb.go",".*/graceTars/.*",".*/.*_test.go", ".*/examples/.*", "/test/.*", "demo/"]