// Copyright (c) 2024 Tencent Inc.
// SPDX-License-Identifier: Apache-2.0
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: api/services/nbi/v1/cubelet_api.proto

package nbi

import (
	v1 "github.com/tencentcloud/CubeSandbox/Cubelet/api/services/errorcode/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestID     string                 `protobuf:"bytes,1,opt,name=requestID,proto3" json:"requestID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_api_services_nbi_v1_cubelet_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_nbi_v1_cubelet_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_api_services_nbi_v1_cubelet_api_proto_rawDescGZIP(), []int{0}
}

func (x *InitRequest) GetRequestID() string {
	if x != nil {
		return x.RequestID
	}
	return ""
}

type InitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestID     string                 `protobuf:"bytes,1,opt,name=requestID,proto3" json:"requestID,omitempty"`
	Code          v1.ErrorCode           `protobuf:"varint,2,opt,name=code,proto3,enum=cubelet.services.errorcode.v1.ErrorCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
	ExtInfo       map[string][]byte      `protobuf:"bytes,4,rep,name=ext_info,json=extInfo,proto3" json:"ext_info,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_api_services_nbi_v1_cubelet_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_services_nbi_v1_cubelet_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_api_services_nbi_v1_cubelet_api_proto_rawDescGZIP(), []int{1}
}

func (x *InitResponse) GetRequestID() string {
	if x != nil {
		return x.RequestID
	}
	return ""
}

func (x *InitResponse) GetCode() v1.ErrorCode {
	if x != nil {
		return x.Code
	}
	return v1.ErrorCode(0)
}

func (x *InitResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InitResponse) GetExtInfo() map[string][]byte {
	if x != nil {
		return x.ExtInfo
	}
	return nil
}

var File_api_services_nbi_v1_cubelet_api_proto protoreflect.FileDescriptor

const file_api_services_nbi_v1_cubelet_api_proto_rawDesc = "" +
	"\n" +
	"%api/services/nbi/v1/cubelet_api.proto\x12\x1bcubelet.services.cubebox.v1\x1a)api/services/errorcode/v1/errorcode.proto\"+\n" +
	"\vInitRequest\x12\x1c\n" +
	"\trequestID\x18\x01 \x01(\tR\trequestID\"\x93\x02\n" +
	"\fInitResponse\x12\x1c\n" +
	"\trequestID\x18\x01 \x01(\tR\trequestID\x12<\n" +
	"\x04code\x18\x02 \x01(\x0e2(.cubelet.services.errorcode.v1.ErrorCodeR\x04code\x12\x18\n" +
	"\aMessage\x18\x03 \x01(\tR\aMessage\x12Q\n" +
	"\bext_info\x18\x04 \x03(\v26.cubelet.services.cubebox.v1.InitResponse.ExtInfoEntryR\aextInfo\x1a:\n" +
	"\fExtInfoEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x012l\n" +
	"\aCubeLet\x12a\n" +
	"\bInitHost\x12(.cubelet.services.cubebox.v1.InitRequest\x1a).cubelet.services.cubebox.v1.InitResponse\"\x00BEZCgithub.com/tencentcloud/CubeSandbox/Cubelet/api/services/nbi/v1;nbib\x06proto3"

var (
	file_api_services_nbi_v1_cubelet_api_proto_rawDescOnce sync.Once
	file_api_services_nbi_v1_cubelet_api_proto_rawDescData []byte
)

func file_api_services_nbi_v1_cubelet_api_proto_rawDescGZIP() []byte {
	file_api_services_nbi_v1_cubelet_api_proto_rawDescOnce.Do(func() {
		file_api_services_nbi_v1_cubelet_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_services_nbi_v1_cubelet_api_proto_rawDesc), len(file_api_services_nbi_v1_cubelet_api_proto_rawDesc)))
	})
	return file_api_services_nbi_v1_cubelet_api_proto_rawDescData
}

var file_api_services_nbi_v1_cubelet_api_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_services_nbi_v1_cubelet_api_proto_goTypes = []any{
	(*InitRequest)(nil),  // 0: cubelet.services.cubebox.v1.InitRequest
	(*InitResponse)(nil), // 1: cubelet.services.cubebox.v1.InitResponse
	nil,                  // 2: cubelet.services.cubebox.v1.InitResponse.ExtInfoEntry
	(v1.ErrorCode)(0),    // 3: cubelet.services.errorcode.v1.ErrorCode
}
var file_api_services_nbi_v1_cubelet_api_proto_depIdxs = []int32{
	3, // 0: cubelet.services.cubebox.v1.InitResponse.code:type_name -> cubelet.services.errorcode.v1.ErrorCode
	2, // 1: cubelet.services.cubebox.v1.InitResponse.ext_info:type_name -> cubelet.services.cubebox.v1.InitResponse.ExtInfoEntry
	0, // 2: cubelet.services.cubebox.v1.CubeLet.InitHost:input_type -> cubelet.services.cubebox.v1.InitRequest
	1, // 3: cubelet.services.cubebox.v1.CubeLet.InitHost:output_type -> cubelet.services.cubebox.v1.InitResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_services_nbi_v1_cubelet_api_proto_init() }
func file_api_services_nbi_v1_cubelet_api_proto_init() {
	if File_api_services_nbi_v1_cubelet_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_services_nbi_v1_cubelet_api_proto_rawDesc), len(file_api_services_nbi_v1_cubelet_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_services_nbi_v1_cubelet_api_proto_goTypes,
		DependencyIndexes: file_api_services_nbi_v1_cubelet_api_proto_depIdxs,
		MessageInfos:      file_api_services_nbi_v1_cubelet_api_proto_msgTypes,
	}.Build()
	File_api_services_nbi_v1_cubelet_api_proto = out.File
	file_api_services_nbi_v1_cubelet_api_proto_goTypes = nil
	file_api_services_nbi_v1_cubelet_api_proto_depIdxs = nil
}
