// Copyright (c) 2024 Tencent Inc.
// SPDX-License-Identifier: Apache-2.0
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.3
// source: api/services/nbi/v1/cubelet_api.proto

package nbi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CubeLet_InitHost_FullMethodName = "/cubelet.services.cubebox.v1.CubeLet/InitHost"
)

// CubeLetClient is the client API for CubeLet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service for machine level operations.
type CubeLetClient interface {
	// Initialize the host, destroy all of the container and initialize metadata.
	// This is a dangerous operation.
	InitHost(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error)
}

type cubeLetClient struct {
	cc grpc.ClientConnInterface
}

func NewCubeLetClient(cc grpc.ClientConnInterface) CubeLetClient {
	return &cubeLetClient{cc}
}

func (c *cubeLetClient) InitHost(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitResponse)
	err := c.cc.Invoke(ctx, CubeLet_InitHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CubeLetServer is the server API for CubeLet service.
// All implementations must embed UnimplementedCubeLetServer
// for forward compatibility.
//
// Service for machine level operations.
type CubeLetServer interface {
	// Initialize the host, destroy all of the container and initialize metadata.
	// This is a dangerous operation.
	InitHost(context.Context, *InitRequest) (*InitResponse, error)
	mustEmbedUnimplementedCubeLetServer()
}

// UnimplementedCubeLetServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCubeLetServer struct{}

func (UnimplementedCubeLetServer) InitHost(context.Context, *InitRequest) (*InitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitHost not implemented")
}
func (UnimplementedCubeLetServer) mustEmbedUnimplementedCubeLetServer() {}
func (UnimplementedCubeLetServer) testEmbeddedByValue()                 {}

// UnsafeCubeLetServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CubeLetServer will
// result in compilation errors.
type UnsafeCubeLetServer interface {
	mustEmbedUnimplementedCubeLetServer()
}

func RegisterCubeLetServer(s grpc.ServiceRegistrar, srv CubeLetServer) {
	// If the following call panics, it indicates UnimplementedCubeLetServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CubeLet_ServiceDesc, srv)
}

func _CubeLet_InitHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CubeLetServer).InitHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CubeLet_InitHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CubeLetServer).InitHost(ctx, req.(*InitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CubeLet_ServiceDesc is the grpc.ServiceDesc for CubeLet service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CubeLet_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cubelet.services.cubebox.v1.CubeLet",
	HandlerType: (*CubeLetServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitHost",
			Handler:    _CubeLet_InitHost_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/services/nbi/v1/cubelet_api.proto",
}
