[changelog]
header = ""
body = """
{% for group, commits in commits | group_by(attribute="group") %}\
### {{ group | striptags | trim | upper_first }}

{% for commit in commits %}\
- {% if commit.scope %}**{{ commit.scope }}**: {% endif %}\
{{ commit.message | upper_first }}\
{% if commit.remote.pr_number %} ([#{{ commit.remote.pr_number }}](https://github.com/kvcache-ai/AgentENV/pull/{{ commit.remote.pr_number }})){% endif %}\
{% if commit.remote.username %} — **@{{ commit.remote.username }}**{% endif %}
{% endfor %}
{% endfor %}\
"""
trim = true
footer = ""

[git]
conventional_commits = true
filter_unconventional = true
filter_commits = false
commit_parsers = [
    { message = "^feat", group = "<!-- 0 -->Features" },
    { message = "^fix", group = "<!-- 1 -->Bug Fixes" },
    { message = "^refactor", group = "<!-- 2 -->Improvements" },
    { message = "^perf", group = "<!-- 3 -->Performance" },
    { message = "^docs?", group = "<!-- 4 -->Documentation" },
    { message = "^ci", skip = true },
    { message = "^chore", skip = true },
    { message = "^style", skip = true },
    { message = "^test", skip = true },
    { message = "^build", skip = true },
]
protect_breaking_commits = true
