apiVersion: v1
kind: Service
metadata:
  name: agentenv-nodes
  labels:
    app.kubernetes.io/name: agentenv-node
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: agentenv-node
  ports:
    - name: http
      port: 8000
      targetPort: http
