// Copyright (c) 2024 Tencent Inc.
// SPDX-License-Identifier: Apache-2.0
//

// Code generated by MockGen. DO NOT EDIT.
// Source: internal/cube/server/images/service.go

// Package images is a generated GoMock package.
package images

import (
	context "context"
	reflect "reflect"

	client "github.com/containerd/containerd/v2/client"
	transfer "github.com/containerd/containerd/v2/core/transfer"
	image "github.com/tencentcloud/CubeSandbox/Cubelet/internal/cube/store/image"
	gomock "go.uber.org/mock/gomock"
	v1 "k8s.io/cri-api/pkg/apis/runtime/v1"
)

type MockimageClient struct {
	ctrl     *gomock.Controller
	recorder *MockimageClientMockRecorder
}

type MockimageClientMockRecorder struct {
	mock *MockimageClient
}

func NewMockimageClient(ctrl *gomock.Controller) *MockimageClient {
	mock := &MockimageClient{ctrl: ctrl}
	mock.recorder = &MockimageClientMockRecorder{mock}
	return mock
}

func (m *MockimageClient) EXPECT() *MockimageClientMockRecorder {
	return m.recorder
}

func (m *MockimageClient) GetImage(arg0 context.Context, arg1 string) (client.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImage", arg0, arg1)
	ret0, _ := ret[0].(client.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockimageClientMockRecorder) GetImage(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImage", reflect.TypeOf((*MockimageClient)(nil).GetImage), arg0, arg1)
}

func (m *MockimageClient) ListImages(arg0 context.Context, arg1 ...string) ([]client.Image, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListImages", varargs...)
	ret0, _ := ret[0].([]client.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockimageClientMockRecorder) ListImages(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListImages", reflect.TypeOf((*MockimageClient)(nil).ListImages), varargs...)
}

func (m *MockimageClient) Pull(arg0 context.Context, arg1 string, arg2 ...client.RemoteOpt) (client.Image, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Pull", varargs...)
	ret0, _ := ret[0].(client.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockimageClientMockRecorder) Pull(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pull", reflect.TypeOf((*MockimageClient)(nil).Pull), varargs...)
}

func (m *MockimageClient) Transfer(ctx context.Context, src, dest interface{}, opts ...transfer.Opt) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, src, dest}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Transfer", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockimageClientMockRecorder) Transfer(ctx, src, dest interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, src, dest}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transfer", reflect.TypeOf((*MockimageClient)(nil).Transfer), varargs...)
}

type MockCubeImageSvcInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCubeImageSvcInterfaceMockRecorder
}

type MockCubeImageSvcInterfaceMockRecorder struct {
	mock *MockCubeImageSvcInterface
}

func NewMockCubeImageSvcInterface(ctrl *gomock.Controller) *MockCubeImageSvcInterface {
	mock := &MockCubeImageSvcInterface{ctrl: ctrl}
	mock.recorder = &MockCubeImageSvcInterfaceMockRecorder{mock}
	return mock
}

func (m *MockCubeImageSvcInterface) EXPECT() *MockCubeImageSvcInterfaceMockRecorder {
	return m.recorder
}

func (m *MockCubeImageSvcInterface) EnsureImage(ctx context.Context, ref, username, password string, config *v1.PodSandboxConfig) (client.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureImage", ctx, ref, username, password, config)
	ret0, _ := ret[0].(client.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockCubeImageSvcInterfaceMockRecorder) EnsureImage(ctx, ref, username, password, config interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureImage", reflect.TypeOf((*MockCubeImageSvcInterface)(nil).EnsureImage), ctx, ref, username, password, config)
}

func (m *MockCubeImageSvcInterface) GetImage(id string) (image.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImage", id)
	ret0, _ := ret[0].(image.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockCubeImageSvcInterfaceMockRecorder) GetImage(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImage", reflect.TypeOf((*MockCubeImageSvcInterface)(nil).GetImage), id)
}

func (m *MockCubeImageSvcInterface) ListImage() []image.Image {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListImage")
	ret0, _ := ret[0].([]image.Image)
	return ret0
}

func (mr *MockCubeImageSvcInterfaceMockRecorder) ListImage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListImage", reflect.TypeOf((*MockCubeImageSvcInterface)(nil).ListImage))
}

func (m *MockCubeImageSvcInterface) LocalResolve(refOrID string) (image.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LocalResolve", refOrID)
	ret0, _ := ret[0].(image.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockCubeImageSvcInterfaceMockRecorder) LocalResolve(refOrID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LocalResolve", reflect.TypeOf((*MockCubeImageSvcInterface)(nil).LocalResolve), refOrID)
}

func (m *MockCubeImageSvcInterface) PullImage(ctx context.Context, name string, credentials func(string) (string, string, error), sandboxConfig *v1.PodSandboxConfig, runtimeHandler string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PullImage", ctx, name, credentials, sandboxConfig, runtimeHandler)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockCubeImageSvcInterfaceMockRecorder) PullImage(ctx, name, credentials, sandboxConfig, runtimeHandler interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PullImage", reflect.TypeOf((*MockCubeImageSvcInterface)(nil).PullImage), ctx, name, credentials, sandboxConfig, runtimeHandler)
}

func (m *MockCubeImageSvcInterface) RemoveImage(ctx context.Context, imageSpec *v1.ImageSpec) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveImage", ctx, imageSpec)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockCubeImageSvcInterfaceMockRecorder) RemoveImage(ctx, imageSpec interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveImage", reflect.TypeOf((*MockCubeImageSvcInterface)(nil).RemoveImage), ctx, imageSpec)
}
