//! Custom extension client: sandbox lifecycle hooks.
//!
//! The custom extension is an external HTTP service configured via
//! `[custom_extension].url`. Its only current capability is sandbox lifecycle
//! hooks, invoked by the sandbox runtime (currently the Firecracker backend):
//!
//! - `POST {url}/sandbox-hook/start-fresh` — before a fresh sandbox boots
//!   (may return extra boot args),
//! - `POST {url}/sandbox-hook/start-resume` — before a sandbox resumes from
//!   a snapshot,
//! - `POST {url}/sandbox-hook/patch-params` — applies an extension-defined
//!   patch to the custom extension params: the patch document is passed
//!   through verbatim and the hook returns the updated full params, which
//!   the runtime stores as the new current value; a failure rejects the
//!   patch,
//! - `POST {url}/sandbox-hook/stop` — when a sandbox stops, before its
//!   network slot is released (best-effort: failures are only logged).
//!
//! Sandbox ids are reused across pause/resume cycles, so each start hook
//! (start-fresh / start-resume) carries a fresh [`SandboxInstanceId`]
//! generated by the sandbox runtime, and the stop hook carries the instance
//! id of the instance being torn down. The extension should treat
//! `(sandbox_id, sandbox_instance_id)` as the identity of a running instance
//! and ignore stop notifications whose instance id is not the latest started
//! instance for that sandbox (stop delivery is best-effort and may be
//! reordered relative to a newer start).
//!
//! Except for the best-effort stop hook, any hook failure (connection error,
//! timeout, non-2xx) fails the corresponding sandbox operation. The client is
//! a process-wide singleton derived from the global config; when no URL is
//! configured, all calls are skipped.

use std::net::Ipv4Addr;
use std::sync::{Arc, OnceLock};
use std::time::Duration;

use anyhow::{Context, Result};
use custom_extension_client::apis::{configuration::Configuration, default_api};
use custom_extension_client::models;
use tracing::{debug, warn};
use uuid::Uuid;

use crate::cfg::ConfigManager;
use crate::types::SandboxId;

/// Unique identifier of one runtime instance of a sandbox, internal to the
/// custom extension lifecycle hooks.
///
/// A fresh value is generated for every sandbox start (fresh boot or resume
/// from a snapshot) when the start hook is delivered; the matching stop hook
/// carries the same value. Together with the sandbox id it disambiguates
/// lifecycle hooks for sandboxes whose id is reused across pause/resume.
#[derive(Clone, Copy, Debug)]
struct SandboxInstanceId(Uuid);

impl SandboxInstanceId {
    fn new() -> Self {
        Self(Uuid::now_v7())
    }
}

impl std::fmt::Display for SandboxInstanceId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.0.fmt(f)
    }
}

/// Process-wide custom extension client, or `None` when
/// `[custom_extension].url` is unset.
static GLOBAL_CLIENT: OnceLock<Option<Arc<CustomExtensionClient>>> = OnceLock::new();

pub(crate) struct CustomExtensionClient {
    configuration: Configuration,
}

impl CustomExtensionClient {
    /// Return the process-wide custom extension client, or `None` when the
    /// custom extension service URL is not configured.
    pub(crate) fn global() -> Option<Arc<CustomExtensionClient>> {
        GLOBAL_CLIENT
            .get_or_init(|| Self::build_from_config().map(Arc::new))
            .clone()
    }

    fn build_from_config() -> Option<CustomExtensionClient> {
        let config = &ConfigManager::global_config().custom_extension;
        let url = config.url.as_deref()?.trim().to_string();
        if url.is_empty() {
            return None;
        }
        let client = match reqwest::Client::builder()
            .timeout(Duration::from_millis(config.timeout_ms))
            .build()
        {
            Ok(client) => client,
            Err(err) => {
                tracing::warn!(
                    error = %err,
                    "failed to build reqwest client for custom extension; \
                     custom extension integration disabled"
                );
                return None;
            }
        };
        Some(CustomExtensionClient {
            configuration: Configuration {
                base_path: url.trim_end_matches('/').to_string(),
                client,
                ..Configuration::default()
            },
        })
    }

    /// Invoke the start-fresh hook: a fresh sandbox is about to boot.
    ///
    /// Returns extra kernel boot args to append, if any.
    async fn hook_start_fresh(
        &self,
        sandbox_id: SandboxId,
        sandbox_instance_id: SandboxInstanceId,
        network_namespace_path: &str,
        host_interaction_ip: Ipv4Addr,
        custom_extension_params: Option<&CustomExtensionParams>,
    ) -> Result<Option<String>> {
        let request = models::StartFreshHookRequest {
            sandbox_id: sandbox_id.to_string(),
            sandbox_instance_id: sandbox_instance_id.to_string(),
            network_namespace_path: network_namespace_path.to_string(),
            host_interaction_ip: host_interaction_ip.to_string(),
            custom_extension_params: Some(
                custom_extension_params
                    .cloned()
                    .map(serde_json::Value::Object)
                    .unwrap_or_else(empty_params),
            ),
        };
        let response = default_api::sandbox_start_fresh(&self.configuration, request)
            .await
            .context("custom extension start-fresh hook failed")?;
        Ok(response.extra_boot_args.flatten())
    }

    /// Invoke the start-resume hook: a sandbox is about to resume from a snapshot.
    async fn hook_start_resume(
        &self,
        sandbox_id: SandboxId,
        sandbox_instance_id: SandboxInstanceId,
        network_namespace_path: &str,
        host_interaction_ip: Ipv4Addr,
        custom_extension_params: Option<&CustomExtensionParams>,
    ) -> Result<()> {
        let request = models::StartResumeHookRequest {
            sandbox_id: sandbox_id.to_string(),
            sandbox_instance_id: sandbox_instance_id.to_string(),
            network_namespace_path: network_namespace_path.to_string(),
            host_interaction_ip: host_interaction_ip.to_string(),
            custom_extension_params: Some(
                custom_extension_params
                    .cloned()
                    .map(serde_json::Value::Object)
                    .unwrap_or_else(empty_params),
            ),
        };
        default_api::sandbox_start_resume(&self.configuration, request)
            .await
            .context("custom extension start-resume hook failed")?;
        Ok(())
    }

    /// Invoke the patch-params hook: apply an extension-defined patch to the
    /// custom extension params.
    ///
    /// The patch document is passed through verbatim; the hook returns the
    /// updated full params (normalized: an absent or empty-object value means
    /// empty params). A failure rejects the patch.
    pub(crate) async fn hook_patch_params(
        &self,
        sandbox_id: SandboxId,
        patch: serde_json::Map<String, serde_json::Value>,
    ) -> Result<Option<CustomExtensionParams>> {
        let request = models::PatchCustomExtensionParamsHookRequest {
            sandbox_id: sandbox_id.to_string(),
            patch: Some(serde_json::Value::Object(patch)),
        };
        let response = default_api::sandbox_patch_params(&self.configuration, request)
            .await
            .context("custom extension patch-params hook failed")?;
        Ok(match response.custom_extension_params {
            None => None,
            Some(value) => match value {
                serde_json::Value::Object(map) => Some(map),
                other => anyhow::bail!(
                    "custom extension patch-params hook returned non-object params: {other}"
                ),
            },
        })
    }

    /// Invoke the stop hook: a sandbox has stopped.
    ///
    /// Fired whenever a sandbox runtime is torn down — including pause
    /// (which stops the VM process and releases the network namespace after
    /// the paused state is persisted; the subsequent resume creates a fresh
    /// runtime and fires start-resume). Stop notification is best-effort:
    /// delivery failures are logged here and never propagated, so callers
    /// (stop() and Drop) share the same fire-and-forget semantics.
    async fn hook_stop(&self, sandbox_id: SandboxId, sandbox_instance_id: SandboxInstanceId) {
        let request = models::StopHookRequest {
            sandbox_id: sandbox_id.to_string(),
            sandbox_instance_id: sandbox_instance_id.to_string(),
        };
        if let Err(err) = default_api::sandbox_stop(&self.configuration, request).await {
            warn!(
                error = %err,
                sandbox_id = %sandbox_id,
                sandbox_instance_id = %sandbox_instance_id,
                "custom extension stop hook failed"
            );
        }
    }
}

/// RAII guard owning the custom extension lifecycle of one sandbox runtime
/// instance.
///
/// Constructed once per runtime via [`CustomExtensionHookGuard::new`];
/// [`CustomExtensionHookGuard::start_fresh`] /
/// [`CustomExtensionHookGuard::start_resume`] then deliver the corresponding
/// start hook, generating a fresh [`SandboxInstanceId`] and recording it
/// *before* the hook is delivered, so that a start hook whose response was
/// lost (e.g. client-side timeout after the extension processed the request)
/// still gets a matching stop on teardown; an extension that never processed
/// the start ignores the stop because the instance id is not its latest
/// started instance.
/// [`CustomExtensionHookGuard::stop`] delivers the stop hook synchronously
/// (awaited) and clears the instance id; dropping a guard that still holds an
/// instance id fires the stop hook fire-and-forget on the current Tokio
/// runtime (never blocking the drop). The stop hook always carries the
/// instance id established by the start hook, so the extension can ignore
/// stop notifications for superseded instances.
pub(crate) struct CustomExtensionHookGuard {
    client: Arc<CustomExtensionClient>,
    sandbox_id: SandboxId,
    /// Instance id established by the start hook (recorded just before the
    /// hook is delivered); `None` while the guard has not started or after
    /// its stop hook was delivered, in which case this guard is inert.
    sandbox_instance_id: Option<SandboxInstanceId>,
}

impl CustomExtensionHookGuard {
    pub(crate) fn new(client: Arc<CustomExtensionClient>, sandbox_id: SandboxId) -> Self {
        Self {
            client,
            sandbox_id,
            sandbox_instance_id: None,
        }
    }

    /// Invoke the start-fresh hook (a fresh sandbox is about to boot).
    ///
    /// Returns the extra kernel boot args returned by the hook, if any.
    pub(crate) async fn start_fresh(
        &mut self,
        network_namespace_path: &str,
        host_interaction_ip: Ipv4Addr,
        custom_extension_params: Option<&CustomExtensionParams>,
    ) -> Result<Option<String>> {
        // Record the instance id before delivering the hook: if the request
        // fails after the extension already processed it (e.g. client-side
        // timeout), teardown still delivers the matching stop.
        let sandbox_instance_id = SandboxInstanceId::new();
        self.sandbox_instance_id = Some(sandbox_instance_id);
        let extra_boot_args = self
            .client
            .hook_start_fresh(
                self.sandbox_id,
                sandbox_instance_id,
                network_namespace_path,
                host_interaction_ip,
                custom_extension_params,
            )
            .await?;
        debug!(
            sandbox_id = %self.sandbox_id,
            sandbox_instance_id = %sandbox_instance_id,
            "custom extension start-fresh hook delivered"
        );
        Ok(extra_boot_args)
    }

    /// Invoke the start-resume hook (a sandbox is about to resume from a
    /// snapshot).
    pub(crate) async fn start_resume(
        &mut self,
        network_namespace_path: &str,
        host_interaction_ip: Ipv4Addr,
        custom_extension_params: Option<&CustomExtensionParams>,
    ) -> Result<()> {
        // Recorded before delivery for the same reason as `start_fresh`.
        let sandbox_instance_id = SandboxInstanceId::new();
        self.sandbox_instance_id = Some(sandbox_instance_id);
        self.client
            .hook_start_resume(
                self.sandbox_id,
                sandbox_instance_id,
                network_namespace_path,
                host_interaction_ip,
                custom_extension_params,
            )
            .await?;
        debug!(
            sandbox_id = %self.sandbox_id,
            sandbox_instance_id = %sandbox_instance_id,
            "custom extension start-resume hook delivered"
        );
        Ok(())
    }

    /// Deliver the stop hook now and clear the instance id.
    pub(crate) async fn stop(mut self) {
        if let Some(sandbox_instance_id) = self.sandbox_instance_id.take() {
            self.client
                .hook_stop(self.sandbox_id, sandbox_instance_id)
                .await;
        }
    }
}

impl Drop for CustomExtensionHookGuard {
    fn drop(&mut self) {
        let Some(sandbox_instance_id) = self.sandbox_instance_id else {
            return;
        };
        let client = Arc::clone(&self.client);
        let sandbox_id = self.sandbox_id;
        match tokio::runtime::Handle::try_current() {
            Ok(handle) => {
                handle.spawn(async move {
                    client.hook_stop(sandbox_id, sandbox_instance_id).await;
                });
            }
            Err(_) => warn!(
                sandbox_id = %sandbox_id,
                sandbox_instance_id = %sandbox_instance_id,
                "sandbox dropped outside a tokio runtime; skipping lifecycle stop hook"
            ),
        }
    }
}

/// Custom extension params: an opaque JSON object interpreted only by the
/// custom extension. `None` and an empty map are equivalent (empty params).
pub(crate) type CustomExtensionParams = serde_json::Map<String, serde_json::Value>;

/// Empty custom extension params (`{}`).
fn empty_params() -> serde_json::Value {
    serde_json::Value::Object(serde_json::Map::new())
}

/// Whether the given params count as empty (absent or an empty map).
pub(crate) fn custom_extension_params_is_empty(params: Option<&CustomExtensionParams>) -> bool {
    match params {
        None => true,
        Some(map) => map.is_empty(),
    }
}

#[cfg(test)]
pub(crate) mod tests {
    use super::*;
    use std::sync::mpsc;
    use tokio::io::{AsyncReadExt, AsyncWriteExt};
    use tokio::net::TcpListener;

    /// Build custom extension params from a JSON object literal.
    fn params(value: serde_json::Value) -> CustomExtensionParams {
        value
            .as_object()
            .expect("params must be a JSON object")
            .clone()
    }

    pub(crate) fn test_client(base: &str) -> CustomExtensionClient {
        CustomExtensionClient {
            configuration: Configuration {
                base_path: base.to_string(),
                client: reqwest::Client::builder()
                    .timeout(Duration::from_secs(2))
                    .build()
                    .unwrap(),
                ..Configuration::default()
            },
        }
    }

    fn find_sub(hay: &[u8], needle: &[u8]) -> Option<usize> {
        hay.windows(needle.len()).position(|w| w == needle)
    }

    /// Read one HTTP request from `stream`, report `(request_line, body)` to
    /// `tx`, and reply with the given status code and JSON body.
    async fn handle_one_request(
        mut stream: tokio::net::TcpStream,
        status: u16,
        body: String,
        tx: mpsc::Sender<(String, String)>,
    ) {
        let mut buf = vec![0u8; 64 * 1024];
        let mut total = 0usize;
        let header_end = loop {
            let n = stream.read(&mut buf[total..]).await.unwrap();
            assert!(n > 0, "connection closed before headers complete");
            total += n;
            if let Some(pos) = find_sub(&buf[..total], b"\r\n\r\n") {
                break pos;
            }
        };
        let headers = String::from_utf8_lossy(&buf[..header_end]).to_string();
        let content_length = headers
            .lines()
            .skip(1)
            .filter_map(|line| line.split_once(':'))
            .find(|(name, _)| name.trim().eq_ignore_ascii_case("content-length"))
            .and_then(|(_, value)| value.trim().parse::<usize>().ok())
            .unwrap_or(0);
        let mut body_bytes = buf[header_end + 4..total].to_vec();
        while body_bytes.len() < content_length {
            let mut tmp = vec![0u8; 64 * 1024];
            let n = stream.read(&mut tmp).await.unwrap();
            assert!(n > 0, "connection closed before body complete");
            body_bytes.extend_from_slice(&tmp[..n]);
        }
        let request_line = headers.lines().next().unwrap().to_string();
        let body_str = String::from_utf8_lossy(&body_bytes[..content_length]).to_string();
        tx.send((request_line, body_str)).unwrap();
        let status_text = match status {
            200 => "OK",
            500 => "Internal Server Error",
            _ => "Unknown",
        };
        let response = format!(
            "HTTP/1.1 {status} {status_text}\r\n\
             Content-Type: application/json\r\n\
             Content-Length: {}\r\n\
             Connection: close\r\n\r\n{}",
            body.len(),
            body
        );
        stream.write_all(response.as_bytes()).await.unwrap();
    }

    /// Spawn an HTTP server that captures `request_count` sequential requests
    /// and replies to each with the given status code and JSON body. Returns
    /// the base URL and a receiver for `(request_line, body)`.
    pub(crate) async fn spawn_test_server(
        status: u16,
        body: String,
        request_count: usize,
    ) -> (String, mpsc::Receiver<(String, String)>) {
        let listener = TcpListener::bind("127.0.0.1:0").await.unwrap();
        let addr = listener.local_addr().unwrap();
        let (tx, rx) = mpsc::channel();
        tokio::spawn(async move {
            for _ in 0..request_count {
                let (stream, _) = listener.accept().await.unwrap();
                handle_one_request(stream, status, body.clone(), tx.clone()).await;
            }
        });
        (format!("http://{addr}"), rx)
    }

    /// Spawn a one-shot HTTP server that captures a single request and replies
    /// with the given status code and JSON body. Returns the base URL and a
    /// receiver for `(request_line, body)`.
    pub(crate) async fn spawn_one_shot_server(
        status: u16,
        body: String,
    ) -> (String, mpsc::Receiver<(String, String)>) {
        spawn_test_server(status, body, 1).await
    }

    #[tokio::test]
    async fn start_fresh_sends_request_and_returns_extra_boot_args() {
        let (base, rx) =
            spawn_one_shot_server(200, r#"{"extraBootArgs":"foo=bar baz"}"#.to_string()).await;
        let client = test_client(&base);
        let sandbox_id = SandboxId::new();
        let sandbox_instance_id = SandboxInstanceId::new();

        let extra = client
            .hook_start_fresh(
                sandbox_id,
                sandbox_instance_id,
                "/var/run/netns/agentenv-ns-test",
                Ipv4Addr::new(10, 11, 0, 123),
                Some(&params(serde_json::json!({"team": "alpha"}))),
            )
            .await
            .expect("start-fresh hook should succeed");

        assert_eq!(extra.as_deref(), Some("foo=bar baz"));
        let (request_line, body) = rx.recv().unwrap();
        assert_eq!(request_line, "POST /sandbox-hook/start-fresh HTTP/1.1");
        let json: serde_json::Value = serde_json::from_str(&body).unwrap();
        assert_eq!(json["sandboxId"], sandbox_id.to_string());
        assert_eq!(json["sandboxInstanceId"], sandbox_instance_id.to_string());
        assert_eq!(
            json["networkNamespacePath"],
            "/var/run/netns/agentenv-ns-test"
        );
        assert_eq!(json["hostInteractionIp"], "10.11.0.123");
        assert_eq!(
            json["customExtensionParams"],
            serde_json::json!({"team": "alpha"})
        );
    }

    #[tokio::test]
    async fn start_fresh_sends_empty_object_when_params_absent() {
        let (base, rx) = spawn_one_shot_server(200, "{}".to_string()).await;
        let client = test_client(&base);

        client
            .hook_start_fresh(
                SandboxId::new(),
                SandboxInstanceId::new(),
                "/var/run/netns/agentenv-ns-test",
                Ipv4Addr::new(10, 11, 0, 124),
                None,
            )
            .await
            .expect("start-fresh hook should succeed");

        let (_, body) = rx.recv().unwrap();
        let json: serde_json::Value = serde_json::from_str(&body).unwrap();
        assert_eq!(json["customExtensionParams"], serde_json::json!({}));
    }

    #[tokio::test]
    async fn start_fresh_non_2xx_fails() {
        let (base, _rx) = spawn_one_shot_server(500, "{}".to_string()).await;
        let client = test_client(&base);

        let err = client
            .hook_start_fresh(
                SandboxId::new(),
                SandboxInstanceId::new(),
                "/var/run/netns/agentenv-ns-test",
                Ipv4Addr::new(10, 11, 0, 125),
                None,
            )
            .await
            .expect_err("non-2xx response must fail the hook");

        assert!(err.to_string().contains("start-fresh hook failed"));
    }

    #[tokio::test]
    async fn start_resume_sends_request() {
        let (base, rx) = spawn_one_shot_server(200, "{}".to_string()).await;
        let client = test_client(&base);
        let sandbox_id = SandboxId::new();
        let sandbox_instance_id = SandboxInstanceId::new();

        client
            .hook_start_resume(
                sandbox_id,
                sandbox_instance_id,
                "/var/run/netns/agentenv-ns-resume",
                Ipv4Addr::new(10, 11, 0, 126),
                None,
            )
            .await
            .expect("start-resume hook should succeed");

        let (request_line, body) = rx.recv().unwrap();
        assert_eq!(request_line, "POST /sandbox-hook/start-resume HTTP/1.1");
        let json: serde_json::Value = serde_json::from_str(&body).unwrap();
        assert_eq!(json["sandboxId"], sandbox_id.to_string());
        assert_eq!(json["sandboxInstanceId"], sandbox_instance_id.to_string());
        assert_eq!(
            json["networkNamespacePath"],
            "/var/run/netns/agentenv-ns-resume"
        );
        assert_eq!(json["hostInteractionIp"], "10.11.0.126");
    }

    #[tokio::test]
    async fn start_guard_stop_carries_matching_instance_id() {
        let (base, rx) = spawn_test_server(200, "{}".to_string(), 2).await;
        let client = Arc::new(test_client(&base));
        let sandbox_id = SandboxId::new();

        let mut guard = CustomExtensionHookGuard::new(client, sandbox_id);
        let extra_boot_args = guard
            .start_fresh(
                "/var/run/netns/agentenv-ns-test",
                Ipv4Addr::new(10, 11, 0, 127),
                None,
            )
            .await
            .expect("start-fresh hook should succeed");
        assert!(extra_boot_args.is_none());
        guard.stop().await;

        let (_, start_body) = rx.recv().unwrap();
        let (_, stop_body) = rx.recv().unwrap();
        let start_json: serde_json::Value = serde_json::from_str(&start_body).unwrap();
        let stop_json: serde_json::Value = serde_json::from_str(&stop_body).unwrap();
        assert_eq!(stop_json["sandboxId"], sandbox_id.to_string());
        assert!(start_json["sandboxInstanceId"].is_string());
        assert_eq!(
            stop_json["sandboxInstanceId"],
            start_json["sandboxInstanceId"]
        );
    }

    #[tokio::test]
    async fn patch_params_passes_patch_and_returns_full_params() {
        let (base, rx) = spawn_one_shot_server(
            200,
            r#"{"customExtensionParams":{"team":"beta","rev":2}}"#.to_string(),
        )
        .await;
        let client = test_client(&base);
        let sandbox_id = SandboxId::new();

        let new_params = client
            .hook_patch_params(
                sandbox_id,
                params(serde_json::json!({"op": "set", "team": "beta"})),
            )
            .await
            .expect("patch-params hook should succeed");

        assert_eq!(
            new_params,
            Some(params(serde_json::json!({"team": "beta", "rev": 2})))
        );
        let (request_line, body) = rx.recv().unwrap();
        assert_eq!(request_line, "POST /sandbox-hook/patch-params HTTP/1.1");
        let json: serde_json::Value = serde_json::from_str(&body).unwrap();
        assert_eq!(json["sandboxId"], sandbox_id.to_string());
        assert_eq!(
            json["patch"],
            serde_json::json!({"op": "set", "team": "beta"})
        );
    }

    #[tokio::test]
    async fn patch_params_maps_empty_response_to_empty_params() {
        // An empty-object response mean empty params
        let (base, _rx) = spawn_one_shot_server(200, "{}".to_string()).await;
        let client = test_client(&base);

        let new_params = client
            .hook_patch_params(SandboxId::new(), params(serde_json::json!({"op": "clear"})))
            .await
            .expect("patch-params hook should succeed");

        assert_eq!(new_params, None);
    }

    #[tokio::test]
    async fn patch_params_non_2xx_fails() {
        let (base, _rx) = spawn_one_shot_server(500, "{}".to_string()).await;
        let client = test_client(&base);

        let err = client
            .hook_patch_params(SandboxId::new(), params(serde_json::json!({})))
            .await
            .expect_err("non-2xx response must fail the hook");

        assert!(err.to_string().contains("patch-params hook failed"));
    }

    #[tokio::test]
    async fn stop_sends_sandbox_and_instance_ids() {
        let (base, rx) = spawn_one_shot_server(200, "{}".to_string()).await;
        let client = test_client(&base);
        let sandbox_id = SandboxId::new();
        let sandbox_instance_id = SandboxInstanceId::new();

        client.hook_stop(sandbox_id, sandbox_instance_id).await;

        let (request_line, body) = rx.recv().unwrap();
        assert_eq!(request_line, "POST /sandbox-hook/stop HTTP/1.1");
        let json: serde_json::Value = serde_json::from_str(&body).unwrap();
        assert_eq!(json["sandboxId"], sandbox_id.to_string());
        assert_eq!(json["sandboxInstanceId"], sandbox_instance_id.to_string());
        assert!(json.get("networkNamespacePath").is_none());
    }

    #[tokio::test]
    async fn hook_guard_stop_delivers_once() {
        let (base, rx) = spawn_test_server(200, "{}".to_string(), 2).await;
        let client = test_client(&base);
        let sandbox_id = SandboxId::new();
        let mut guard = CustomExtensionHookGuard::new(Arc::new(client), sandbox_id);
        guard
            .start_resume(
                "/var/run/netns/agentenv-ns-resume",
                Ipv4Addr::new(10, 11, 0, 128),
                None,
            )
            .await
            .expect("start-resume hook should succeed");

        guard.stop().await;

        let (_, start_body) = rx.recv().unwrap();
        let (request_line, stop_body) = rx.recv().unwrap();
        assert_eq!(request_line, "POST /sandbox-hook/stop HTTP/1.1");
        let start_json: serde_json::Value = serde_json::from_str(&start_body).unwrap();
        let stop_json: serde_json::Value = serde_json::from_str(&stop_body).unwrap();
        assert_eq!(stop_json["sandboxId"], sandbox_id.to_string());
        assert_eq!(
            stop_json["sandboxInstanceId"],
            start_json["sandboxInstanceId"]
        );
        // The stop hook was delivered and the instance id cleared: dropping
        // the guard now must not re-fire (the two-shot server would not
        // accept a third request anyway).
    }

    #[tokio::test]
    async fn failed_start_still_stops_on_drop_with_matching_instance_id() {
        // The instance id is recorded before the start hook is delivered, so
        // even a failed start (e.g. the extension processed the request but
        // its response was lost) gets a matching stop on teardown; an
        // extension that never processed the start ignores it.
        let (base, rx) = spawn_test_server(500, "{}".to_string(), 2).await;
        let client = test_client(&base);
        let sandbox_id = SandboxId::new();

        {
            let mut guard = CustomExtensionHookGuard::new(Arc::new(client), sandbox_id);
            guard
                .start_fresh(
                    "/var/run/netns/agentenv-ns-test",
                    Ipv4Addr::new(10, 11, 0, 129),
                    None,
                )
                .await
                .expect_err("start-fresh hook must fail on non-2xx");
        } // dropped while armed: must fire the stop hook fire-and-forget

        let (start_request_line, start_body) = rx.recv().unwrap();
        assert_eq!(
            start_request_line,
            "POST /sandbox-hook/start-fresh HTTP/1.1"
        );
        // The notification is spawned on this runtime; poll for it without
        // blocking the (single-threaded) test runtime.
        let (request_line, body) = tokio::time::timeout(std::time::Duration::from_secs(5), async {
            loop {
                if let Ok(msg) = rx.try_recv() {
                    break msg;
                }
                tokio::task::yield_now().await;
            }
        })
        .await
        .expect("stop hook should fire on drop even after a failed start");
        assert_eq!(request_line, "POST /sandbox-hook/stop HTTP/1.1");
        let start_json: serde_json::Value = serde_json::from_str(&start_body).unwrap();
        let json: serde_json::Value = serde_json::from_str(&body).unwrap();
        assert_eq!(json["sandboxId"], sandbox_id.to_string());
        assert_eq!(json["sandboxInstanceId"], start_json["sandboxInstanceId"]);
    }

    #[tokio::test]
    async fn hook_guard_fires_on_drop() {
        let (base, rx) = spawn_test_server(200, "{}".to_string(), 2).await;
        let client = test_client(&base);
        let sandbox_id = SandboxId::new();

        {
            let mut guard = CustomExtensionHookGuard::new(Arc::new(client), sandbox_id);
            guard
                .start_fresh(
                    "/var/run/netns/agentenv-ns-test",
                    Ipv4Addr::new(10, 11, 0, 130),
                    None,
                )
                .await
                .expect("start-fresh hook should succeed");
        } // dropped: must fire the stop hook fire-and-forget

        let (start_request_line, start_body) = rx.recv().unwrap();
        assert_eq!(
            start_request_line,
            "POST /sandbox-hook/start-fresh HTTP/1.1"
        );
        // The notification is spawned on this runtime; poll for it without
        // blocking the (single-threaded) test runtime.
        let (request_line, body) = tokio::time::timeout(std::time::Duration::from_secs(5), async {
            loop {
                if let Ok(msg) = rx.try_recv() {
                    break msg;
                }
                tokio::time::sleep(std::time::Duration::from_millis(10)).await;
            }
        })
        .await
        .expect("stop hook should fire on drop");
        assert_eq!(request_line, "POST /sandbox-hook/stop HTTP/1.1");
        let start_json: serde_json::Value = serde_json::from_str(&start_body).unwrap();
        let json: serde_json::Value = serde_json::from_str(&body).unwrap();
        assert_eq!(json["sandboxId"], sandbox_id.to_string());
        assert_eq!(json["sandboxInstanceId"], start_json["sandboxInstanceId"]);
        assert!(json.get("networkNamespacePath").is_none());
    }
}
